Unified Edit Specifications
===

These specified edits are based on comparisons between published and regenerated summary data

In [1]:
import pandas as pd
import numpy as np

### Constants

In [2]:
keep_columns = [
        "surveyyear",
        "lab",
        "stationid",
        "toxbatch",
        "species",
        "dilution",
        "fieldreplicate",
        "sampletypecode",
        "pvalue",
        "mean",
        "control_mean",
        "pctcontrol",
        "stddev",
        "coefficientvariance",
        "n",
        "units",
        "qacode",
        "treatment",
        "comments",
        "matrix",
        "sigeffect",
        "endpoint",
        "sqocategory",
        "unify_comment",
        "unify_action",
    ]

## Read in unified summary dataset

In [3]:
df = pd.read_excel("unified_dataset_freeze_2025.08.21_1259/unified.xlsx").replace(np.nan, None)
df.head()

objectid  surveyyear                                       lab stationid  \
0         1        1994  Science Applications International Corp.      0016   
1         2        1994  Science Applications International Corp.      0032   
2         3        1994  Science Applications International Corp.      0115   
3         4        1994  Science Applications International Corp.      0150   
4         5        1994  Science Applications International Corp.      0365   

  toxbatch           species dilution  fieldreplicate sampletypecode  \
0   940939  Ampelisca abdita     None               1         Result   
1   940939  Ampelisca abdita     None               1         Result   
2   940939  Ampelisca abdita     None               1         Result   
3   940939  Ampelisca abdita     None               1         Result   
4   940939  Ampelisca abdita     None               1         Result   

     pvalue  ...       units qacode treatment comments          matrix  \
0   0.08658  ...  percentage      A      None     None  Whole Sediment   
1  0.158067  ...  percentage      A      None     None  Whole Sediment   
2  0.036322  ...  percentage      A      None     None  Whole Sediment   
3  0.222882  ...  percentage      A      None     None  Whole Sediment   
4  0.015915  ...  percentage      A      None     None  Whole Sediment   

   sigeffect                 endpoint sqo_category_value_initial Score  \
0        NSC  10 day survival percent                       None  None   
1        NSC  10 day survival percent                       None  None   
2         SC  10 day survival percent                       None  None   
3        NSC  10 day survival percent                       None  None   
4         SC  10 day survival percent                       None  None   

  sqocategory  
0        None  
1        None  
2        None  
3        None  
4        None  

[5 rows x 26 columns]

## Specs for 2023

In [4]:
# Fix 2023

pub_23_path = "compare_2025.08.21/2023/bight23summary.xlsx"
pub_2023 = pd.read_excel(pub_23_path, sheet_name="bight23summary")

uni_2023 = df[df["surveyyear"] == 2023]
uni_2023


objectid  surveyyear                                           lab  \
4378      4379        2023  Aquatic Bioassay and Consulting Laboratories   
4379      4380        2023  Aquatic Bioassay and Consulting Laboratories   
4380      4381        2023  Aquatic Bioassay and Consulting Laboratories   
4381      4382        2023  Aquatic Bioassay and Consulting Laboratories   
4382      4383        2023  Aquatic Bioassay and Consulting Laboratories   
...        ...         ...                                           ...   
4901      4902        2023                                           WSP   
4902      4903        2023                                           WSP   
4903      4904        2023                                           WSP   
4904      4905        2023                                           WSP   
4905      4906        2023                                           WSP   

      stationid                toxbatch                        species  \
4378       0000                  ABC001      Mytilus galloprovincialis   
4379       0000                  ABC002         Eohaustorius estuarius   
4380       0000                  ABC003  Strongylocentrotus purpuratus   
4381       0000           EOH081523_B23         Eohaustorius estuarius   
4382       0000           EOH081823_B23         Eohaustorius estuarius   
...         ...                     ...                            ...   
4901  B23-12363  23-10-019 to 23-10-033      Mytilus galloprovincialis   
4902  B23-12366       23-10-001 to -018         Eohaustorius estuarius   
4903  B23-12366  23-10-019 to 23-10-033      Mytilus galloprovincialis   
4904  B23-12841       23-09-001 to -018         Eohaustorius estuarius   
4905  B23-12841  23-09-019 to 23-09-036      Mytilus galloprovincialis   

     dilution  fieldreplicate sampletypecode    pvalue  ...       units  \
4378     None               1           CNEG       0.5  ...  percentage   
4379     None               1           CNEG       0.5  ...  percentage   
4380     None               1           CNEG       0.5  ...  percentage   
4381     None               1           CNEG       0.5  ...  percentage   
4382     None               1           CNEG       0.5  ...  percentage   
...       ...             ...            ...       ...  ...         ...   
4901     None               1         Result  0.464153  ...  percentage   
4902     None               1         Result  0.008065  ...  percentage   
4903     None               1         Result  0.095549  ...  percentage   
4904     None               1         Result  0.064819  ...  percentage   
4905     None               1         Result  0.013521  ...  percentage   

     qacode treatment                                           comments  \
4378      A      None                                               None   
4379      A      None                                               None   
4380      A      None                                               None   
4381      A      None                                               None   
4382      A      None                                               None   
...     ...       ...                                                ...   
4901      A      None  Replicate equilibrated an additional 24 hours ...   
4902      A      None                                 Salinity at 17 ppt   
4903      A      None  Replicate equilibrated an additional 24 hours ...   
4904      A      None                                               None   
4905      A      None                                               None   

                        matrix  sigeffect                 endpoint  \
4378  Sediment Water Interface        NSC     Percent normal-alive   
4379            Whole Sediment        NSC  10 day survival percent   
4380  Sediment Water Interface        NSC     Percent normal-alive   
4381            Whole Sediment        NSC  10 day survival percent   
4382            Whole Sediment        NS

In [5]:
# Check if there are any non-standard stationids
uni_2023[~uni_2023.stationid.str.startswith("B") & ~uni_2023.stationid.str.startswith("0")]

Empty DataFrame
Columns: [objectid, surveyyear, lab, stationid, toxbatch, species, dilution, fieldreplicate, sampletypecode, pvalue, mean, control_mean, pctcontrol, stddev, coefficientvariance, n, units, qacode, treatment, comments, matrix, sigeffect, endpoint, sqo_category_value_initial, Score, sqocategory]
Index: []

[0 rows x 26 columns]

In [6]:
# Delete keys
delete_key_columns = ["stationid", "toxbatch", "lab", "species"]
delete_2023 = pd.read_excel("compare_2025.08.21/2023/compare-2023.xlsx", "deletions")
delete_2023

unify_comment unify_action stationid  \
0      Intercal rows shouldn't be published       DELETE   SampleA   
1      Intercal rows shouldn't be published       DELETE   SampleB   
2      Intercal rows shouldn't be published       DELETE   SampleC   
3      Intercal rows shouldn't be published       DELETE   SampleD   
4      Intercal rows shouldn't be published       DELETE   SampleA   
5      Intercal rows shouldn't be published       DELETE   SampleB   
6      Intercal rows shouldn't be published       DELETE   SampleC   
7      Intercal rows shouldn't be published       DELETE   SampleD   
8      Intercal rows shouldn't be published       DELETE   SampleA   
9      Intercal rows shouldn't be published       DELETE   SampleB   
10     Intercal rows shouldn't be published       DELETE   SampleC   
11     Intercal rows shouldn't be published       DELETE   SampleD   
12     Intercal rows shouldn't be published       DELETE   SampleA   
13     Intercal rows shouldn't be published       DELETE   SampleB   
14     Intercal rows shouldn't be published       DELETE   SampleC   
15     Intercal rows shouldn't be published       DELETE   SampleD   
16     Intercal rows shouldn't be published       DELETE   SampleA   
17     Intercal rows shouldn't be published       DELETE   SampleB   
18     Intercal rows shouldn't be published       DELETE   SampleC   
19     Intercal rows shouldn't be published       DELETE   SampleD   
20   Only have CNEG/Intercal. Don't publish       DELETE      0000   
21   Only have CNEG/Intercal. Don't publish       DELETE      0000   
22   Only have CNEG/Intercal. Don't publish       DELETE      0000   
23   Only have CNEG/Intercal. Don't publish       DELETE      0000   
24         Only have CNEG/QA. Don't publish       DELETE       NaN   
25         Only have CNEG/QA. Don't publish       DELETE       NaN   
26         Only have CNEG/QA. Don't publish       DELETE       NaN   
27         Only have CNEG/QA. Don't publish       DELETE       NaN   
28         Only have CNEG/QA. Don't publish       DELETE       NaN   
29         Only have CNEG/QA. Don't publish       DELETE       NaN   
30         Only have CNEG/QA. Don't publish       DELETE       NaN   
31         Only have CNEG/QA. Don't publish       DELETE       NaN   
32  RFNH3/CNEG/Intercal only. Don't publish       DELETE      0000   

               toxbatch                                           lab  \
0             2303-S210                                      Enthalpy   
1             2303-S210                                      Enthalpy   
2             2303-S210                                      Enthalpy   
3             2303-S210                                      Enthalpy   
4                ABC003  Aquatic Bioassay and Consulting Laboratories   
5                ABC003  Aquatic Bioassay and Consulting Laboratories   
6                ABC003  Aquatic Bioassay and Consulting Laboratories   
7                ABC003  Aquatic Bioassay and Consulting Laboratories   
8          NIWC-2023-SP      Naval Information Warfare Center Pacific   
9          NIWC-2023-SP      Naval Information Warfare Center Pacific   
10         NIWC-2023-SP      Naval Information Warfare Center Pacific   
11         NIWC-2023-SP      Naval Information Warfare Center Pacific   
12            PG1788S.p                                   EcoAnalysts   
13            PG1788S.p                                   EcoAnalysts   
14            PG1788S.p                                   EcoAnalysts   
15            PG1788S.p                                   EcoAnalysts   
16               WSP003                                           WSP   
17               WSP003                                           WSP   
18               WSP003                                           WSP   
19               WSP003                                           WSP   
20            2303-S210                                      Enthalpy   
21         NIWC-2023-SP      Naval Informat

In [7]:
merged = pd.merge(uni_2023, delete_2023, on=delete_key_columns, how="left").replace(
    np.nan, None
)
# merged.loc[merged.unify_action=='DELETE']
merged.columns

Index(['objectid', 'surveyyear', 'lab', 'stationid', 'toxbatch', 'species',
       'dilution', 'fieldreplicate', 'sampletypecode', 'pvalue', 'mean',
       'control_mean', 'pctcontrol', 'stddev', 'coefficientvariance', 'n',
       'units', 'qacode', 'treatment', 'comments', 'matrix', 'sigeffect',
       'endpoint', 'sqo_category_value_initial', 'Score', 'sqocategory',
       'unify_comment', 'unify_action'],
      dtype='object')

In [8]:
uni_2023_correct = merged[keep_columns]


In [9]:
# Check if there are any no-operation rows
uni_2023_correct[uni_2023_correct.unify_action.isnull()]

surveyyear                                           lab  stationid  \
0          2023  Aquatic Bioassay and Consulting Laboratories       0000   
1          2023  Aquatic Bioassay and Consulting Laboratories       0000   
3          2023  Aquatic Bioassay and Consulting Laboratories       0000   
4          2023  Aquatic Bioassay and Consulting Laboratories       0000   
5          2023  Aquatic Bioassay and Consulting Laboratories       0000   
..          ...                                           ...        ...   
523        2023                                           WSP  B23-12363   
524        2023                                           WSP  B23-12366   
525        2023                                           WSP  B23-12366   
526        2023                                           WSP  B23-12841   
527        2023                                           WSP  B23-12841   

                   toxbatch                    species dilution  \
0                    ABC001  Mytilus galloprovincialis     None   
1                    ABC002     Eohaustorius estuarius     None   
3             EOH081523_B23     Eohaustorius estuarius     None   
4             EOH081823_B23     Eohaustorius estuarius     None   
5             EOH082923_B23     Eohaustorius estuarius     None   
..                      ...                        ...      ...   
523  23-10-019 to 23-10-033  Mytilus galloprovincialis     None   
524       23-10-001 to -018     Eohaustorius estuarius     None   
525  23-10-019 to 23-10-033  Mytilus galloprovincialis     None   
526       23-09-001 to -018     Eohaustorius estuarius     None   
527  23-09-019 to 23-09-036  Mytilus galloprovincialis     None   

     fieldreplicate sampletypecode    pvalue    mean  ...       units qacode  \
0                 1           CNEG       0.5   96.94  ...  percentage      A   
1                 1           CNEG       0.5    99.0  ...  percentage      A   
3                 1           CNEG       0.5    99.0  ...  percentage      A   
4                 1           CNEG       0.5    99.0  ...  percentage      A   
5                 1           CNEG       0.5    99.0  ...  percentage      A   
..              ...            ...       ...     ...  ...         ...    ...   
523               1         Result  0.464153  88.956  ...  percentage      A   
524               1         Result  0.008065    92.0  ...  percentage      A   
525               1         Result  0.095549  84.444  ...  percentage      A   
526               1         Result  0.064819    93.0  ...  percentage      A   
527               1         Result  0.013521  78.044  ...  percentage      A   

    treatment                                           comments  \
0        None                                               None   
1        None                                               None   
3        None                                               None   
4        None                                               None   
5        None                                               None   
..        ...                                                ...   
523      None  Replicate equilibrated an additional 24 hours ...   
524      None                                 Salinity at 17 ppt   
525      None  Replicate equilibrated an additional 24 hours ...   
526      None                                               None   
527      None                                               None   

                       matrix sigeffect                 endpoint  \
0    Sediment Water Interface       NSC     Percent normal-alive   
1              Whole Sediment       NSC  10 day survival percent   
3              Whole Sediment       NSC  10 day survival percent   
4              Whole Sediment       NSC  10 day survival percent   
5              Whole Sediment       NSC  10 day survival percent   
..                        ...       ...                      ...   
523  Sediment Water Interface    

In [10]:
# Check if there are any DELETE rows
uni_2023_correct[uni_2023_correct.unify_action == "DELETE"]

surveyyear                                           lab stationid  \
2          2023  Aquatic Bioassay and Consulting Laboratories      0000   
167        2023                                   EcoAnalysts      0000   
169        2023                                      Enthalpy      0000   
249        2023      Naval Information Warfare Center Pacific      0000   
354        2023                                           WSP      0000   

         toxbatch                        species dilution  fieldreplicate  \
2          ABC003  Strongylocentrotus purpuratus     None               1   
167     PG1788S.p  Strongylocentrotus purpuratus     None               1   
169     2303-S210  Strongylocentrotus purpuratus     None               1   
249  NIWC-2023-SP  Strongylocentrotus purpuratus     None               1   
354        WSP003  Strongylocentrotus purpuratus     None               1   

    sampletypecode pvalue       mean  ...       units qacode treatment  \
2             CNEG    0.5      97.58  ...  percentage      A      None   
167           CNEG    0.5     60.094  ...  percentage      D      None   
169           CNEG    0.5  91.445087  ...  percentage      A      None   
249           CNEG    0.5  96.377079  ...  percentage      A      None   
354           CNEG    0.5      95.79  ...  percentage      A      None   

                comments                    matrix sigeffect  \
2                   None  Sediment Water Interface       NSC   
167                 None  Sediment Water Interface       NSC   
169                 None  Sediment Water Interface       NSC   
249  Screen Tube Control  Sediment Water Interface       NSC   
354                 None  Sediment Water Interface       NSC   

                 endpoint sqocategory  \
2    Percent normal-alive        None   
167  Percent normal-alive        None   
169  Percent normal-alive        None   
249  Percent normal-alive        None   
354  Percent normal-alive        None   

                               unify_comment unify_action  
2    RFNH3/CNEG/Intercal only. Don't publish       DELETE  
167   Only have CNEG/Intercal. Don't publish       DELETE  
169   Only have CNEG/Intercal. Don't publish       DELETE  
249   Only have CNEG/Intercal. Don't publish       DELETE  
354   Only have CNEG/Intercal. Don't publish       DELETE  

[5 rows x 25 columns]

In [11]:
# Check if there are control rows with a category
uni_2023_correct[uni_2023_correct.sampletypecode == "CNEG"].sqocategory.unique()

array([None], dtype=object)

In [12]:
unify_2023_correct = uni_2023_correct.copy()

## Specs for 2018

In [13]:
pub_18_path = "compare_2025.08.21/2018/Bight_18_Sediment_Toxicity_Summary_Results_9058230620704627381.xlsx"
pub_2018 = pd.read_excel(pub_18_path)
pub_2018.head()

objectid  stationid  latitude  longitude  stationwaterdepth  \
0         5  B18-10118  32.69040  -117.2342               14.1   
1         6  B18-10120  32.68950  -117.2380               12.8   
2         7  B18-10120  32.68950  -117.2380               12.8   
3         8  B18-10122  32.68720  -117.2339               11.2   
4         9  B18-10045  34.25844  -119.2669                3.0   

  stationwaterdepthunits  stratum                                      lab  \
0                      m    Ports  Space and Naval Warfare Systems Command   
1                      m    Ports  Space and Naval Warfare Systems Command   
2                      m    Ports  Space and Naval Warfare Systems Command   
3                      m    Ports  Space and Naval Warfare Systems Command   
4                      m  Marinas  Los Angeles County Sanitation Districts   

  sampletypecode      toxbatch  ... dilution fieldreplicate  \
0           Grab   SSC-2018-MG  ...      -88              1   
1           Grab  SSC-2018-EOH  ...      -88              1   
2           Grab   SSC-2018-MG  ...      -88              1   
3           Grab  SSC-2018-EOH  ...      -88              1   
4           Grab    8/28B18eea  ...      -88              1   

                     matrix   samplecollectdate  treatment  \
0  Sediment Water Interface 2018-08-08 07:00:00        NaN   
1            Whole Sediment 2018-08-08 07:00:00        NaN   
2  Sediment Water Interface 2018-08-08 07:00:00        NaN   
3            Whole Sediment 2018-08-08 07:00:00        NaN   
4            Whole Sediment 2018-08-18 07:00:00        NaN   

                                 globalid  areaweight  gdb_geomattr_data  \
0  {8ACAFA8A-944E-4713-88AC-4BA1995196A6}    0.190988                NaN   
1  {559C29A9-5A8B-49C1-9393-44130B801111}    0.190988                NaN   
2  {9BD6414B-2F74-4882-91AA-27B4D4FFD4A9}    0.190988                NaN   
3  {332DA3A8-40F1-4962-82D0-B549D2876B70}    0.190988                NaN   
4  {5AEF37BD-34A5-4CF4-A618-59338FAB9F4C}    0.374061                NaN   

          x         y  
0 -117.2342  32.69040  
1 -117.2380  32.68950  
2 -117.2380  32.68950  
3 -117.2339  32.68720  
4 -119.2669  34.25844  

[5 rows x 33 columns]

In [14]:
uni_2018 = df[df["surveyyear"] == 2018]
uni_2018

objectid  surveyyear                                      lab  \
3838      3839        2018           AMEC, Foster, & Wheeler / WOOD   
3839      3840        2018           AMEC, Foster, & Wheeler / WOOD   
3840      3841        2018           AMEC, Foster, & Wheeler / WOOD   
3841      3842        2018           AMEC, Foster, & Wheeler / WOOD   
3842      3843        2018           AMEC, Foster, & Wheeler / WOOD   
...        ...         ...                                      ...   
4373      4374        2018  Space and Naval Warfare Systems Command   
4374      4375        2018  Space and Naval Warfare Systems Command   
4375      4376        2018  Space and Naval Warfare Systems Command   
4376      4377        2018  Space and Naval Warfare Systems Command   
4377      4378        2018  Space and Naval Warfare Systems Command   

      stationid                         toxbatch                    species  \
3838       0000   18-07-003 to-006; -011 to -014     Eohaustorius estuarius   
3839       0000  18-07-007 to -010; -015 to -018  Mytilus galloprovincialis   
3840       0000                18-07-019 to -027     Eohaustorius estuarius   
3841       0000                18-07-028 to -036  Mytilus galloprovincialis   
3842       0000                18-07-053 to -065     Eohaustorius estuarius   
...         ...                              ...                        ...   
4373  B18-10138                      SSC-2018-MG  Mytilus galloprovincialis   
4374  B18-10447                     SSC-2018-EOH     Eohaustorius estuarius   
4375  B18-10447                      SSC-2018-MG  Mytilus galloprovincialis   
4376  B18-10465                     SSC-2018-EOH     Eohaustorius estuarius   
4377  B18-10465                      SSC-2018-MG  Mytilus galloprovincialis   

     dilution  fieldreplicate sampletypecode    pvalue  ...       units  \
3838     None               1           CNEG       0.5  ...  percentage   
3839     None               1           CNEG       0.5  ...  percentage   
3840     None               1           CNEG       0.5  ...  percentage   
3841     None               1           CNEG       0.5  ...  percentage   
3842     None               1           CNEG       0.5  ...  percentage   
...       ...             ...            ...       ...  ...         ...   
4373     None               1         Result  0.159738  ...  percentage   
4374     None               1         Result  0.121438  ...  percentage   
4375     None               1         Result  0.466088  ...  percentage   
4376     None               1         Result  0.121438  ...  percentage   
4377     None               1         Result  0.420482  ...  percentage   

     qacode treatment comments                    matrix  sigeffect  \
3838      A      None     None            Whole Sediment        NSC   
3839      A      None     None  Sediment Water Interface        NSC   
3840      A      None     None            Whole Sediment        NSC   
3841      A      None     None  Sediment Water Interface        NSC   
3842      A      None     None            Whole Sediment        NSC   
...     ...       ...      ...                       ...        ...   
4373      A      None     None  Sediment Water Interface        NSC   
4374      A      None     None            Whole Sediment        NSC   
4375      A      None     None  Sediment Water Interface        NSC   
4376      A      None     None            Whole Sediment        NSC   
4377      A      None     None  Sediment Water Interface        NSC   

                     endpoint sqo_category_value_initial Score sqocategory  
3838  10 day survival percent                       None  None        None  
3839     Percent normal-alive                       None  None        None  
3840  10 day survival percent                       None  None        None  
3841     Percent normal-alive                       None  None        None  
3842  10 day survival percent                       None  None   

In [15]:
comparison_2018 = pd.read_excel('compare_2025.08.21/2018/compare-2018.xlsx').rename({
    "COMMENTS": "unify_comment",
    "ACTION": "unify_action",
    "lab.uni": "lab",
    "species.uni": "species"
}, axis=1).replace(np.nan, None)[delete_key_columns + ["unify_action", "unify_comment"]]

delete_2018 = comparison_2018.unify_action == "DELETE"

delete_2018.value_counts()

unify_action
False    541
True      19
Name: count, dtype: int64

In [16]:
comparison_2018 = pd.read_excel('compare_2025.08.21/2018/compare-2018.xlsx').rename({
    "COMMENTS": "unify_comment",
    "ACTION": "unify_action",
    "lab.uni": "lab",
    "species.uni": "species"
}, axis=1).replace(np.nan, None)[delete_key_columns + ["unify_action", "unify_comment"]]
comparison_2018.unify_action.value_counts()

unify_action
EDIT      90
DELETE    19
Name: count, dtype: int64

In [17]:
delete_2018_loc = comparison_2018.unify_action == "DELETE"
delete_2018_loc

0      False
1      False
2      False
3      False
4      False
       ...  
555    False
556    False
557    False
558    False
559    False
Name: unify_action, Length: 560, dtype: bool

In [18]:
delete_2018 = comparison_2018[delete_2018_loc]
pd.merge(uni_2018, delete_2018[['stationid', 'toxbatch']], how='inner')

Empty DataFrame
Columns: [objectid, surveyyear, lab, stationid, toxbatch, species, dilution, fieldreplicate, sampletypecode, pvalue, mean, control_mean, pctcontrol, stddev, coefficientvariance, n, units, qacode, treatment, comments, matrix, sigeffect, endpoint, sqo_category_value_initial, Score, sqocategory]
Index: []

[0 rows x 26 columns]

In [19]:
edits_2018 = comparison_2018.loc[comparison_2018.unify_action == "EDIT"]
print(len(edits_2018))
edits_2018.unify_comment.unique()

90


array(["CNEG shouldn't have published category. Delete category.",
       "CNEG shouldn't have published category. Missing Pvalue in UNI. Use published Pvalue (0.04056309)"],
      dtype=object)

In [20]:
edit_cat_2018_loc = (comparison_2018.unify_action == "EDIT") & (comparison_2018.unify_comment == "CNEG shouldn't have published category. Delete category.")
edit_cat_2018 = comparison_2018[edit_cat_2018_loc]
edit_cat_2018
pd.merge(uni_2018, edit_cat_2018[['stationid', 'toxbatch']], how='inner')

objectid  surveyyear                                      lab stationid  \
0       3839        2018           AMEC, Foster, & Wheeler / WOOD      0000   
1       3840        2018           AMEC, Foster, & Wheeler / WOOD      0000   
2       3841        2018           AMEC, Foster, & Wheeler / WOOD      0000   
3       3842        2018           AMEC, Foster, & Wheeler / WOOD      0000   
4       3843        2018           AMEC, Foster, & Wheeler / WOOD      0000   
..       ...         ...                                      ...       ...   
84      4306        2018                   Nautilus Environmental      0000   
85      4307        2018                   Nautilus Environmental      0000   
86      4334        2018       Orange County Sanitation Districts      0000   
87      4345        2018  Space and Naval Warfare Systems Command      0000   
88      4346        2018  Space and Naval Warfare Systems Command      0000   

                           toxbatch                    species dilution  \
0    18-07-003 to-006; -011 to -014     Eohaustorius estuarius     None   
1   18-07-007 to -010; -015 to -018  Mytilus galloprovincialis     None   
2                 18-07-019 to -027     Eohaustorius estuarius     None   
3                 18-07-028 to -036  Mytilus galloprovincialis     None   
4                 18-07-053 to -065     Eohaustorius estuarius     None   
..                              ...                        ...      ...   
84                   1809-S165-S169  Mytilus galloprovincialis     None   
85                   1809-S170-S174     Eohaustorius estuarius     None   
86                             OCSD     Eohaustorius estuarius     None   
87                     SSC-2018-EOH     Eohaustorius estuarius     None   
88                      SSC-2018-MG  Mytilus galloprovincialis     None   

    fieldreplicate sampletypecode pvalue  ...       units qacode treatment  \
0                1           CNEG    0.5  ...  percentage      A      None   
1                1           CNEG    0.5  ...  percentage      A      None   
2                1           CNEG    0.5  ...  percentage      A      None   
3                1           CNEG    0.5  ...  percentage      A      None   
4                1           CNEG    0.5  ...  percentage      A      None   
..             ...            ...    ...  ...         ...    ...       ...   
84               1           CNEG    0.5  ...  percentage      A      None   
85               1           CNEG   None  ...  percentage      A      None   
86               1           CNEG   None  ...  percentage      A      None   
87               1           CNEG    0.5  ...  percentage      A      None   
88               1           CNEG    0.5  ...  percentage      A      None   

               comments                    matrix  sigeffect  \
0                  None            Whole Sediment        NSC   
1                  None  Sediment Water Interface        NSC   
2                  None            Whole Sediment        NSC   
3                  None  Sediment Water Interface        NSC   
4                  None            Whole Sediment        NSC   
..                  ...                       ...        ...   
84                 None  Sediment Water Interface        NSC   
85                 None            Whole Sediment       None   
86                 None            Whole Sediment       None   
87  Yaquina Bay Control            Whole Sediment        NSC   
88  Screen Tube Control  Sediment Water Interface        NSC   

                   endpoint sqo_category_value_initial Score sqocategory  
0   10 day survival percent                       None  None        None  
1      Percent normal-alive                       None  None        None  
2   10 day survival percent                       None  None        None  
3      Percent normal-alive                       None  None        None  
4   10 day survival percent                       None  None        None 

In [21]:
edit_pvalue_2018_loc = (comparison_2018.unify_action == "EDIT") & (comparison_2018.unify_comment == "CNEG shouldn't have published category. Missing Pvalue in UNI. Use published Pvalue (0.04056309)")
edit_pvalue_2018 = comparison_2018[edit_pvalue_2018_loc]
edit_pvalue_2018
pd.merge(uni_2018, edit_pvalue_2018[['stationid', 'toxbatch']], how='inner')

objectid  surveyyear                             lab stationid  \
0      3871        2018  AMEC, Foster, & Wheeler / WOOD      0000   

                  toxbatch                 species dilution  fieldreplicate  \
0  18-09-028 to -030; -034  Eohaustorius estuarius     None               1   

  sampletypecode pvalue  ...       units qacode treatment comments  \
0           CNEG   None  ...  percentage      A      None     None   

           matrix  sigeffect                 endpoint  \
0  Whole Sediment       None  10 day survival percent   

  sqo_category_value_initial Score sqocategory  
0                       None  None        None  

[1 rows x 26 columns]

In [22]:
actions_2018 = pd.concat([delete_2018, edit_cat_2018, edit_pvalue_2018])
actions_2018.unify_action.value_counts()

unify_action
EDIT      90
DELETE    19
Name: count, dtype: int64

In [23]:
actions_2018[actions_2018.unify_comment.str.contains('Pval')]

stationid                 toxbatch                             lab  \
549      0000  18-09-028 to -030; -034  AMEC, Foster, & Wheeler / WOOD   

                    species unify_action  \
549  Eohaustorius estuarius         EDIT   

                                         unify_comment  
549  CNEG shouldn't have published category. Missin...

In [24]:
merged_2018 = pd.merge(uni_2018, actions_2018, on=delete_key_columns, how="left").replace(np.nan, None)
merged_2018.loc[(merged_2018.stationid == '0000') & (merged_2018.toxbatch == '18-09-028 to -030; -034'), 'pvalue'] = 0.04056309
merged_2018.loc[(merged_2018.stationid == '0000') & (merged_2018.toxbatch == '18-09-028 to -030; -034')]

objectid  surveyyear                             lab stationid  \
32      3871        2018  AMEC, Foster, & Wheeler / WOOD      0000   

                   toxbatch                 species dilution  fieldreplicate  \
32  18-09-028 to -030; -034  Eohaustorius estuarius     None               1   

   sampletypecode    pvalue  ... treatment comments          matrix sigeffect  \
32           CNEG  0.040563  ...      None     None  Whole Sediment      None   

                   endpoint  sqo_category_value_initial Score sqocategory  \
32  10 day survival percent                        None  None        None   

   unify_action                                      unify_comment  
32         EDIT  CNEG shouldn't have published category. Missin...  

[1 rows x 28 columns]

In [25]:
uni_2018_correct = merged_2018[keep_columns]

In [26]:
# Check that the single P value was corrected
uni_2018_correct[(uni_2018_correct.stationid == '0000') & (uni_2018_correct.toxbatch == '18-09-028 to -030; -034')]

surveyyear                             lab stationid  \
32        2018  AMEC, Foster, & Wheeler / WOOD      0000   

                   toxbatch                 species dilution  fieldreplicate  \
32  18-09-028 to -030; -034  Eohaustorius estuarius     None               1   

   sampletypecode    pvalue   mean  ...       units qacode treatment comments  \
32           CNEG  0.040563  100.0  ...  percentage      A      None     None   

            matrix sigeffect                 endpoint sqocategory  \
32  Whole Sediment      None  10 day survival percent        None   

                                        unify_comment unify_action  
32  CNEG shouldn't have published category. Missin...         EDIT  

[1 rows x 25 columns]

In [27]:
# Check that all CNEG rows have null SQO Category
uni_2018_correct.loc[(uni_2018_correct.sampletypecode == "CNEG") & ~uni_2018_correct.sqocategory.isnull()]

Empty DataFrame
Columns: [surveyyear, lab, stationid, toxbatch, species, dilution, fieldreplicate, sampletypecode, pvalue, mean, control_mean, pctcontrol, stddev, coefficientvariance, n, units, qacode, treatment, comments, matrix, sigeffect, endpoint, sqocategory, unify_comment, unify_action]
Index: []

[0 rows x 25 columns]

In [28]:
unify_2018_correct = uni_2018_correct.copy()

## Specs for 2013

In [29]:
uni_2013 = df[df["surveyyear"] == 2013]
uni_2013.head()

objectid  surveyyear                                           lab  \
3351      3352        2013  Aquatic Bioassay and Consulting Laboratories   
3352      3353        2013  Aquatic Bioassay and Consulting Laboratories   
3353      3354        2013  Aquatic Bioassay and Consulting Laboratories   
3354      3355        2013  Aquatic Bioassay and Consulting Laboratories   
3355      3356        2013  Aquatic Bioassay and Consulting Laboratories   

     stationid    toxbatch                    species dilution  \
3351      0000   B13071613  Mytilus galloprovincialis     None   
3352      0000  B13072313E     Eohaustorius estuarius     None   
3353      0000   B13072413  Mytilus galloprovincialis     None   
3354      0000   B13080713  Mytilus galloprovincialis     None   
3355      0000   B13082813  Mytilus galloprovincialis     None   

      fieldreplicate sampletypecode pvalue  ...       units qacode treatment  \
3351               1           CNEG    0.5  ...  percentage      A      None   
3352               1           CNEG    0.5  ...  percentage      A      None   
3353               1           CNEG    0.5  ...  percentage      A      None   
3354               1           CNEG    0.5  ...  percentage      A      None   
3355               1           CNEG    0.5  ...  percentage      A      None   

     comments                    matrix  sigeffect                 endpoint  \
3351     None  Sediment Water Interface        NSC     Percent normal-alive   
3352     None            Whole Sediment        NSC  10 day survival percent   
3353     None  Sediment Water Interface        NSC     Percent normal-alive   
3354     None  Sediment Water Interface        NSC     Percent normal-alive   
3355     None  Sediment Water Interface        NSC     Percent normal-alive   

     sqo_category_value_initial Score sqocategory  
3351                       None  None        None  
3352                       None  None        None  
3353                       None  None        None  
3354                       None  None        None  
3355                       None  None        None  

[5 rows x 26 columns]

In [30]:
compare_2013 = pd.read_excel(
    "compare_2025.08.21/2013/compare-2013.xlsx", "compare"
).replace(np.nan, None)
edits_2013 = compare_2013[~compare_2013.unify_action.isnull()].rename({'species.uni': 'species'}, axis=1)
edits_2013

unify_comment unify_action  \
7                          Wasn't originally published          ADD   
16                         Wasn't originally published          ADD   
24                         Wasn't originally published          ADD   
33                         Wasn't originally published          ADD   
39                         Wasn't originally published          ADD   
..                                                 ...          ...   
499  Pub/Uni means don't match. Mean 0 in pub doesn...      COMMENT   
500  Pub/Uni means don't match. Mean 0 in pub doesn...      COMMENT   
501                        Wasn't originally published          ADD   
512              Sample type QA shouldn't be published       DELETE   
513                        Wasn't originally published          ADD   

     surveyyear stationid           toxbatch       Category.pub  \
7          2013      0000  1307-S070 to S076               None   
16         2013      0000  1307-S077 to S084               None   
24         2013      0000  1307-S085 to S091               None   
33         2013      0000  1307-S092 to S099               None   
39         2013      0000  1307-S159 to S165               None   
..          ...       ...                ...                ...   
499        2013  B13-8391         nacSed0926       Low Toxicity   
500        2013  B13-8413         nacSed0926  Moderate Toxicity   
501        2013      0000         nacSed0926               None   
512        2013  B13-8325              OCSD1           Nontoxic   
513        2013      0000              OCSD1               None   

          Category.uni  Category.zcomp sampletypecode.pub sampletypecode.uni  \
7                 None           False               None               CNEG   
16                None           False               None               CNEG   
24                None           False               None               CNEG   
33                None           False               None               CNEG   
39                None           False               None               CNEG   
..                 ...             ...                ...                ...   
499       Low Toxicity            True               Grab             Result   
500  Moderate Toxicity            True               Grab             Result   
501               None           False               None               CNEG   
512               None           False                 QA               None   
513               None           False               None               CNEG   

     ... Unnamed: 53 stationwaterdepth stationwaterdepthunits statisticaltest  \
7    ...       False              None                   None            None   
16   ...       False              None                   None            None   
24   ...       False              None                   None            None   
33   ...       False              None                   None            None   
39   ...       False              None                   None            None   
..   ...         ...               ...                    ...             ...   
499  ...        True              20.0                     Ft       UV T-test   
500  ...        True               4.0                      M       UV T-test   
501  ...       False              None                   None            None   
512  ...       False              14.0                      M       UV T-test   
513  ...       False              None                   None            None   

       stratum treatment units.pub units.uni           x          y  
7         None      None      None      None        None       None  
16        None      None      None      None        None       None  
24        None      None      None      None        None       None  
33        None      None      None      None        None       None  
39        None      None      None      None        None       None  
..         ...       ...     

In [31]:
edits_2013.unify_action.value_counts()

unify_action
ADD        65
DELETE     46
COMMENT     8
Name: count, dtype: int64

In [32]:
add_batches = set(edits_2013.loc[edits_2013.unify_action== 'ADD'].toxbatch)
counts = (uni_2013.loc[uni_2013.toxbatch.isin(add_batches)][['toxbatch', 'stationid', 'species', 'sampletypecode']]
    .groupby(['toxbatch', 'species'])
    .count()
    .reset_index())
# Unifies summary toxbatches without Results
uni_2013[uni_2013.toxbatch.isin(counts[counts.sampletypecode == 1].toxbatch)]

Empty DataFrame
Columns: [objectid, surveyyear, lab, stationid, toxbatch, species, dilution, fieldreplicate, sampletypecode, pvalue, mean, control_mean, pctcontrol, stddev, coefficientvariance, n, units, qacode, treatment, comments, matrix, sigeffect, endpoint, sqo_category_value_initial, Score, sqocategory]
Index: []

[0 rows x 26 columns]

In [33]:
edits_tack = edits_2013[['stationid', 'toxbatch', 'species', 'unify_comment', 'unify_action']]
edits_tack

stationid           toxbatch                    species  \
7        0000  1307-S070 to S076     Eohaustorius estuarius   
16       0000  1307-S077 to S084     Eohaustorius estuarius   
24       0000  1307-S085 to S091  Mytilus galloprovincialis   
33       0000  1307-S092 to S099  Mytilus galloprovincialis   
39       0000  1307-S159 to S165     Eohaustorius estuarius   
..        ...                ...                        ...   
499  B13-8391         nacSed0926   Neanthes arenaceodentata   
500  B13-8413         nacSed0926   Neanthes arenaceodentata   
501      0000         nacSed0926   Neanthes arenaceodentata   
512  B13-8325              OCSD1                       None   
513      0000              OCSD1     Eohaustorius estuarius   

                                         unify_comment unify_action  
7                          Wasn't originally published          ADD  
16                         Wasn't originally published          ADD  
24                         Wasn't originally published          ADD  
33                         Wasn't originally published          ADD  
39                         Wasn't originally published          ADD  
..                                                 ...          ...  
499  Pub/Uni means don't match. Mean 0 in pub doesn...      COMMENT  
500  Pub/Uni means don't match. Mean 0 in pub doesn...      COMMENT  
501                        Wasn't originally published          ADD  
512              Sample type QA shouldn't be published       DELETE  
513                        Wasn't originally published          ADD  

[119 rows x 5 columns]

In [34]:
edits_tack[['unify_comment', 'unify_action']].value_counts()

unify_comment                                                                                                            unify_action
Wasn't originally published                                                                                              ADD             65
Sample type QA shouldn't be published                                                                                    DELETE          20
CNEG/QA only shouldn't be in summary                                                                                     DELETE          14
No QA Code A results                                                                                                     DELETE          12
Pub/Uni means don't match. Mean 0 in pub doesn't match Results                                                           COMMENT          6
Pub/Uni means don't match. Uni stddev matches Results data                                                               COMMENT          1
Pub/Uni means don't match.

In [35]:
unify_2013_correct = pd.merge(uni_2013, edits_tack, how="left").replace(np.nan, None)
unify_2013_correct

objectid  surveyyear                                           lab  \
0        3352        2013  Aquatic Bioassay and Consulting Laboratories   
1        3353        2013  Aquatic Bioassay and Consulting Laboratories   
2        3354        2013  Aquatic Bioassay and Consulting Laboratories   
3        3355        2013  Aquatic Bioassay and Consulting Laboratories   
4        3356        2013  Aquatic Bioassay and Consulting Laboratories   
..        ...         ...                                           ...   
482      3834        2013            Orange County Sanitation Districts   
483      3835        2013            Orange County Sanitation Districts   
484      3836        2013            Orange County Sanitation Districts   
485      3837        2013            Orange County Sanitation Districts   
486      3838        2013            Orange County Sanitation Districts   

    stationid    toxbatch                    species dilution  fieldreplicate  \
0        0000   B13071613  Mytilus galloprovincialis     None               1   
1        0000  B13072313E     Eohaustorius estuarius     None               1   
2        0000   B13072413  Mytilus galloprovincialis     None               1   
3        0000   B13080713  Mytilus galloprovincialis     None               1   
4        0000   B13082813  Mytilus galloprovincialis     None               1   
..        ...         ...                        ...      ...             ...   
482  B13-9178       OCSD1     Eohaustorius estuarius     None               1   
483  B13-9193       OCSD1     Eohaustorius estuarius     None               1   
484  B13-9197       OCSD1     Eohaustorius estuarius     None               1   
485  B13-9199       OCSD1     Eohaustorius estuarius     None               1   
486  B13-9204       OCSD1     Eohaustorius estuarius     None               1   

    sampletypecode    pvalue  ... treatment comments  \
0             CNEG       0.5  ...      None     None   
1             CNEG       0.5  ...      None     None   
2             CNEG       0.5  ...      None     None   
3             CNEG       0.5  ...      None     None   
4             CNEG       0.5  ...      None     None   
..             ...       ...  ...       ...      ...   
482         Result  0.126992  ...      None     None   
483         Result  0.335358  ...      None     None   
484         Result  0.152033  ...      None     None   
485         Result       0.5  ...      None     None   
486         Result  0.341658  ...      None     None   

                       matrix sigeffect                 endpoint  \
0    Sediment Water Interface       NSC     Percent normal-alive   
1              Whole Sediment       NSC  10 day survival percent   
2    Sediment Water Interface       NSC     Percent normal-alive   
3    Sediment Water Interface       NSC     Percent normal-alive   
4    Sediment Water Interface       NSC     Percent normal-alive   
..                        ...       ...                      ...   
482            Whole Sediment       NSC  10 day survival percent   
483            Whole Sediment       NSC  10 day survival percent   
484            Whole Sediment       NSC  10 day survival percent   
485            Whole Sediment       NSC  10 day survival percent   
486            Whole Sediment       NSC  10 day survival percent   

     sqo_category_value_initial Score sqocategory  \
0                          None  None        None   
1                          None  None        None   
2                          None  None        None   
3                          None  None        None   
4                          None  None        None   
..                          ...   ...         ...   
482                         1.0   1.0    Nontoxic   
483                         1.0   1.0    Nontoxic   
484                         1.0   1.0    Nontoxic   
485                         1.0   1.0    Nontoxic   
486                         1.0   1.0    Nontoxic   

    

In [36]:
# Check CNEG rows do not have SQO category
unify_2013_correct[(unify_2013_correct.sampletypecode == "CNEG") & (~unify_2013_correct.sqocategory.isnull())]

Empty DataFrame
Columns: [objectid, surveyyear, lab, stationid, toxbatch, species, dilution, fieldreplicate, sampletypecode, pvalue, mean, control_mean, pctcontrol, stddev, coefficientvariance, n, units, qacode, treatment, comments, matrix, sigeffect, endpoint, sqo_category_value_initial, Score, sqocategory, unify_comment, unify_action]
Index: []

[0 rows x 28 columns]

In [37]:
# How many unify actions are there?
unify_2013_correct.unify_action.value_counts()

unify_action
ADD        65
DELETE     19
COMMENT     8
Name: count, dtype: int64

#### What unapplied edits are there?
These are specified in the compare Excel file, but not present in the Unified summary

In [38]:
edits_tack[['toxbatch', 'species', 'unify_action', 'unify_comment']]

toxbatch                    species unify_action  \
7    1307-S070 to S076     Eohaustorius estuarius          ADD   
16   1307-S077 to S084     Eohaustorius estuarius          ADD   
24   1307-S085 to S091  Mytilus galloprovincialis          ADD   
33   1307-S092 to S099  Mytilus galloprovincialis          ADD   
39   1307-S159 to S165     Eohaustorius estuarius          ADD   
..                 ...                        ...          ...   
499         nacSed0926   Neanthes arenaceodentata      COMMENT   
500         nacSed0926   Neanthes arenaceodentata      COMMENT   
501         nacSed0926   Neanthes arenaceodentata          ADD   
512              OCSD1                       None       DELETE   
513              OCSD1     Eohaustorius estuarius          ADD   

                                         unify_comment  
7                          Wasn't originally published  
16                         Wasn't originally published  
24                         Wasn't originally published  
33                         Wasn't originally published  
39                         Wasn't originally published  
..                                                 ...  
499  Pub/Uni means don't match. Mean 0 in pub doesn...  
500  Pub/Uni means don't match. Mean 0 in pub doesn...  
501                        Wasn't originally published  
512              Sample type QA shouldn't be published  
513                        Wasn't originally published  

[119 rows x 4 columns]

#### Note these have no species

Not in the generated unified dataset. Checks out.

In [39]:
check_unapplied_edits_2013 = pd.merge(edits_tack[['toxbatch', 'species', 'unify_action', 'unify_comment']], unify_2013_correct.drop(['unify_comment', 'unify_action'], axis=1), how="left", indicator=True)
check_unapplied_edits_2013[check_unapplied_edits_2013['_merge'] == 'left_only']

toxbatch species unify_action  \
60   1307-S200 to S201    None       DELETE   
61   1307-S200 to S201    None       DELETE   
64   1307-S202 to S203    None       DELETE   
65   1307-S202 to S203    None       DELETE   
355         B13072313E    None       DELETE   
356         B13072313E    None       DELETE   
359          B13072413    None       DELETE   
411           CLAEMD2B    None       DELETE   
412           CLAEMD2B    None       DELETE   
470             CSD005    None       DELETE   
471             CSD005    None       DELETE   
472             CSD005    None       DELETE   
477             CSD007    None       DELETE   
478             CSD007    None       DELETE   
545         EohSed0809    None       DELETE   
569          EohSed719    None       DELETE   
570          EohSed719    None       DELETE   
583         mgcSed0814    None       DELETE   
584         mgcSed0814    None       DELETE   
647              OCSD1    None       DELETE   

                             unify_comment  objectid  surveyyear  lab  \
60   Sample type QA shouldn't be published       NaN         NaN  NaN   
61   Sample type QA shouldn't be published       NaN         NaN  NaN   
64   Sample type QA shouldn't be published       NaN         NaN  NaN   
65   Sample type QA shouldn't be published       NaN         NaN  NaN   
355  Sample type QA shouldn't be published       NaN         NaN  NaN   
356  Sample type QA shouldn't be published       NaN         NaN  NaN   
359  Sample type QA shouldn't be published       NaN         NaN  NaN   
411  Sample type QA shouldn't be published       NaN         NaN  NaN   
412  Sample type QA shouldn't be published       NaN         NaN  NaN   
470  Sample type QA shouldn't be published       NaN         NaN  NaN   
471  Sample type QA shouldn't be published       NaN         NaN  NaN   
472  Sample type QA shouldn't be published       NaN         NaN  NaN   
477  Sample type QA shouldn't be published       NaN         NaN  NaN   
478  Sample type QA shouldn't be published       NaN         NaN  NaN   
545  Sample type QA shouldn't be published       NaN         NaN  NaN   
569  Sample type QA shouldn't be published       NaN         NaN  NaN   
570  Sample type QA shouldn't be published       NaN         NaN  NaN   
583  Sample type QA shouldn't be published       NaN         NaN  NaN   
584  Sample type QA shouldn't be published       NaN         NaN  NaN   
647  Sample type QA shouldn't be published       NaN         NaN  NaN   

    stationid dilution  fieldreplicate  ... qacode treatment comments matrix  \
60        NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
61        NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
64        NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
65        NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
355       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
356       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
359       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
411       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
412       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
470       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
471       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
472       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
477       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
478       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
545       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
569       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
570       NaN      NaN             NaN  ...    NaN       NaN      NaN    NaN   
583       NaN      NaN             NaN  ...    NaN  

## Specs for 2008

In [40]:
uni_2008 = df[df["surveyyear"] == 2008]
pub_2008 = pd.read_excel("compare_2025.08.21/2008/B08CEToxicitySummaryResults_CE.xlsx")
comp_2008 = (pd.read_excel('compare_2025.08.21/2008/compare-2008.xlsx', 'Sheet 1')
    .rename({"COMMENT": "unify_comment", "ACTION": "unify_action"}, axis=1)
    .replace(np.nan, None)
    [['stationid', 'toxbatch', 'sampletypecode.uni', 'species.uni', 'unify_comment', 'unify_action']])
edits = comp_2008[comp_2008.unify_action == "EDIT"]
deletes = comp_2008[comp_2008.unify_action == "DELETE"]
comments = comp_2008[comp_2008.unify_action == "COMMENT"]
len(uni_2008)

486

### EDITs

In [41]:
edits[['unify_comment', 'unify_action']].value_counts()

unify_comment                                                                                          unify_action
Pub sigdiff doesn't correspond properly to pval. Use pub except for sigdiff and pval.                  EDIT            17
Pub pctcontrol correct; edit control mean to 90.33                                                     EDIT            11
Pub has NSC for sigdiff, but P value below 0.05. Use UNI sigdiff                                       EDIT             2
Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5  EDIT             2
Uni using control mean 93, should be 90.33. Pub sigdiff doesn't correspond properly to pval.           EDIT             2
Name: count, dtype: int64

In [42]:
unify_deleted = pd.merge(uni_2008, deletes).replace(np.nan, None)
unify_commented = pd.merge(uni_2008, comments).replace(np.nan, None)
unify_edited = pd.merge(uni_2008, edits).replace(np.nan, None)

#### EDIT 1

"Pub sigdiff doesn't correspond properly to pval. Use pub except for sigdiff and pval."

In [43]:
# Pub sigdiff doesn't correspond properly to pval. Use pub except for sigdiff and pval. 
edits_1 = edits[edits.unify_comment == "Pub sigdiff doesn't correspond properly to pval. Use pub except for sigdiff and pval."]
pub = pub_2008.rename({
    "StationID": "stationid",
    "SampleType": "sampletypecode",
    "QABatch": "toxbatch",
    "Species": "species",
}, axis=1)
pub.species.value_counts()
pub = pub.replace(to_replace=["EE", "MG"], value=["Eohaustorius estuarius", "Mytilus galloprovincialis"])
pub['stationid'] = pub['stationid'].astype(str)
pub['sampletypecode'] = pub['sampletypecode'].str.upper()
pub = pub.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
pub

LabCode  \
stationid toxbatch       sampletypecode species                             
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius         WS   
          B08MGTJR       RESULT         Mytilus galloprovincialis      WS   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius         WS   
          B08MGTJR       RESULT         Mytilus galloprovincialis      WS   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius         WS   
...                                                                   ...   
GS00      B08EE090508    QA             Eohaustorius estuarius         WS   
          B08EE090908    QA             Eohaustorius estuarius         WS   
          B08EELPLSELTJR QA             Eohaustorius estuarius         WS   
          B08EESDR       QA             Eohaustorius estuarius         WS   
SC12      B08EESEL6242   CNEG           Eohaustorius estuarius         WS   

                                                                   Dilution  \
stationid toxbatch       sampletypecode species                               
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius          -99   
          B08MGTJR       RESULT         Mytilus galloprovincialis       -99   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius          -99   
          B08MGTJR       RESULT         Mytilus galloprovincialis       -99   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius          -99   
...                                                                     ...   
GS00      B08EE090508    QA             Eohaustorius estuarius          -99   
          B08EE090908    QA             Eohaustorius estuarius          -99   
          B08EELPLSELTJR QA             Eohaustorius estuarius          -99   
          B08EESDR       QA             Eohaustorius estuarius          -99   
SC12      B08EESEL6242   CNEG           Eohaustorius estuarius          -99   

                                                                   Concentration  \
stationid toxbatch       sampletypecode species                                    
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius               -99   
          B08MGTJR       RESULT         Mytilus galloprovincialis            -99   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius               -99   
          B08MGTJR       RESULT         Mytilus galloprovincialis            -99   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius               -99   
...                                                                          ...   
GS00      B08EE090508    QA             Eohaustorius estuarius               -99   
          B08EE090908    QA             Eohaustorius estuarius               -99   
          B08EELPLSELTJR QA             Eohaustorius estuarius               -99   
          B08EESDR       QA             Eohaustorius estuarius               -99   
SC12      B08EESEL6242   CNEG           Eohaustorius estuarius               -99   

                                                                  EPCode  \
stationid toxbatch       sampletypecode species                            
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius      SP10   
          B08MGTJR       RESULT         Mytilus galloprovincialis    NPA   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius      SP10   
          B08MGTJR       RESULT         Mytilus galloprovincialis    NPA   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius      SP10   
...                                                                  ...   
GS00      B08EE090508    QA             Eohaustorius estuarius      SP10   
          B08EE090908    QA             Eohaustorius estuarius      SP10   
          B08EELPLSELTJR QA             Eohaustorius estuarius      SP10   
          B08EESDR       QA             Eohaustorius estuarius      SP10   
SC12      B08EESEL6242   CNEG  

In [44]:
edits_01 = edits_1.rename({
    'sampletypecode.uni': 'sampletypecode',
    'species.uni': 'species'}, axis=1)
edits_01.sampletypecode = edits_01.sampletypecode.str.upper()
edits_01.stationid = edits_01.stationid.astype(str)
edits_01 = edits_01.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
indexer = edits_01.index.to_flat_index().tolist()
indexer = pub.index.intersection(indexer)

In [45]:
uni_2008.columns

Index(['objectid', 'surveyyear', 'lab', 'stationid', 'toxbatch', 'species',
       'dilution', 'fieldreplicate', 'sampletypecode', 'pvalue', 'mean',
       'control_mean', 'pctcontrol', 'stddev', 'coefficientvariance', 'n',
       'units', 'qacode', 'treatment', 'comments', 'matrix', 'sigeffect',
       'endpoint', 'sqo_category_value_initial', 'Score', 'sqocategory'],
      dtype='object')

In [46]:
pub_vals = pub.loc[indexer][['Mean', "N", "StdDev", "PctControl"]].rename({
    "Mean": "mean",
    "N": "n",
    "StdDev": "stddev", 
    "PctControl": "pctcontrol"
}, axis=1)
uni_2008.loc[:, "sampletypecode"] = uni_2008.sampletypecode.str.upper()

uni_2008_0 = uni_2008.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species']) 
indexer = uni_2008_0.index.intersection(pub_vals.index.to_flat_index().tolist())
uni_2008_0.loc[indexer]
uni_to_join = uni_2008_0.drop(['mean','n','stddev','pctcontrol'], axis=1).loc[indexer]
pub_to_join = pub_vals.loc[indexer]
joined = uni_to_join.join(pub_to_join)
joined[['unify_comment', 'unify_action']] = (
    "Pub sigdiff doesn't correspond properly to pval. Use pub except for sigdiff and pval.",
    "EDIT")
EDIT_1 = joined.copy()
EDIT_1

objectid  \
stationid toxbatch        sampletypecode species                               
6363      GC_B08MG3_S_TOX RESULT         Mytilus galloprovincialis      2989   
6375      GC_B08EE6_S_TOX RESULT         Eohaustorius estuarius         2992   
6068      B08EE090908     RESULT         Eohaustorius estuarius         3169   
6080      B08MG12         RESULT         Mytilus galloprovincialis      3179   
6094      B08EE090508     RESULT         Eohaustorius estuarius         3193   
6181      B08EESDR        RESULT         Eohaustorius estuarius         3260   
6189      B08EESDR        RESULT         Eohaustorius estuarius         3262   
6192      B08EESDR        RESULT         Eohaustorius estuarius         3264   
6197      B08EESDR        RESULT         Eohaustorius estuarius         3266   
6200      B08EESDR        RESULT         Eohaustorius estuarius         3268   
6288      B08EE082608     RESULT         Eohaustorius estuarius         3318   
6303      B08MG091008     RESULT         Mytilus galloprovincialis      3325   
6308      B08MG091008     RESULT         Mytilus galloprovincialis      3327   
6311      B08MG091008     RESULT         Mytilus galloprovincialis      3329   
6317      B08MG091008     RESULT         Mytilus galloprovincialis      3333   
6327      B08EE082608     RESULT         Eohaustorius estuarius         3338   
6328      B08EE082608     RESULT         Eohaustorius estuarius         3340   

                                                                    surveyyear  \
stationid toxbatch        sampletypecode species                                 
6363      GC_B08MG3_S_TOX RESULT         Mytilus galloprovincialis        2008   
6375      GC_B08EE6_S_TOX RESULT         Eohaustorius estuarius           2008   
6068      B08EE090908     RESULT         Eohaustorius estuarius           2008   
6080      B08MG12         RESULT         Mytilus galloprovincialis        2008   
6094      B08EE090508     RESULT         Eohaustorius estuarius           2008   
6181      B08EESDR        RESULT         Eohaustorius estuarius           2008   
6189      B08EESDR        RESULT         Eohaustorius estuarius           2008   
6192      B08EESDR        RESULT         Eohaustorius estuarius           2008   
6197      B08EESDR        RESULT         Eohaustorius estuarius           2008   
6200      B08EESDR        RESULT         Eohaustorius estuarius           2008   
6288      B08EE082608     RESULT         Eohaustorius estuarius           2008   
6303      B08MG091008     RESULT         Mytilus galloprovincialis        2008   
6308      B08MG091008     RESULT         Mytilus galloprovincialis        2008   
6311      B08MG091008     RESULT         Mytilus galloprovincialis        2008   
6317      B08MG091008     RESULT         Mytilus galloprovincialis        2008   
6327      B08EE082608     RESULT         Eohaustorius estuarius           2008   
6328      B08EE082608     RESULT         Eohaustorius estuarius           2008   

                                                                                                            lab  \
stationid toxbatch        sampletypecode species                                                                  
6363      GC_B08MG3_S_TOX RESULT         Mytilus galloprovincialis  Granite Canyon Marine Pollution Studies Lab   
6375      GC_B08EE6_S_TOX RESULT         Eohaustorius estuarius     Granite Canyon Marine Pollution Studies Lab   
6068      B08EE090908     RESULT         Eohaustorius estuarius                                Weston Solutions   
6080      B08MG12         RESULT         Mytilus galloprovincialis                             Weston Solutions   
6094      B08EE090508     RESULT         Eohaustorius estuarius                                Weston Solutions   
6181      B08EESDR        RESULT         Eohaustorius estuarius                                Weston Solutions   
6189      B08EESDR        RESULT         Eohaustorius estuarius     

#### EDIT 2

"Pub pctcontrol correct; edit control mean to 90.33"

In [47]:
# Prepare edits

edits_2 = (edits[edits.unify_comment == "Pub pctcontrol correct; edit control mean to 90.33"]
    .rename({"sampletypecode.uni": "sampletypecode", "species.uni": "species"}, axis=1))
edits_2.loc[:, 'stationid'] = edits_2.stationid.astype(str)
edits_2.loc[:, 'sampletypecode'] = edits_2.sampletypecode.str.upper()
edits_2 = edits_2.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
pub = pub_2008.rename({
    "StationID": "stationid",
    "SampleType": "sampletypecode",
    "QABatch": "toxbatch",
    "Species": "species",
    "PctControl": "pctcontrol",
}, axis=1)
pub['stationid'] = pub['stationid'].astype(str)
pub['sampletypecode'] = pub['sampletypecode'].str.upper()
pub = pub.replace(to_replace=["EE", "MG"], value=["Eohaustorius estuarius", "Mytilus galloprovincialis"])
pub = pub.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])[['pctcontrol']]
indexer = pub.index.intersection(edits_2.index).to_flat_index().tolist()
uni_2008_2 = uni_2008.copy()
uni_2008_2.loc[:, 'stationid'] = uni_2008_2.stationid.astype(str)
uni_2008_2.loc[:, 'sampletypecode'] = uni_2008_2.sampletypecode.str.upper()
uni_2008_2 = uni_2008_2.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
uni_2008_2 = uni_2008_2.drop('pctcontrol', axis=1)
EDIT_2 = uni_2008_2.join(pub).loc[indexer]
EDIT_2[['unify_comment', 'unify_action']] = (
    "Pub pctcontrol correct; edit control mean to 90.33",
    "EDIT"
)
EDIT_2.control_mean = 90.33
EDIT_2

objectid  \
stationid toxbatch       sampletypecode species                            
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3122   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3124   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3126   
6010      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3128   
6228      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3278   
6229      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3280   
6230      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3282   
6232      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3284   
6236      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3286   
6243      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3292   
6245      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3296   

                                                                surveyyear  \
stationid toxbatch       sampletypecode species                              
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6010      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6228      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6229      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6230      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6232      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6236      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6243      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6245      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   

                                                                             lab  \
stationid toxbatch       sampletypecode species                                    
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6010      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6228      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6229      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6230      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6232      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6236      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6243      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6245      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   

                                                               dilution  \
stationid toxbatch       sampletypecode species                           
6001      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6004      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6009      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6010      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6228      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6229      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6230      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6232      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6236      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6243      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6245      B08EELPLSELTJR RESULT         Eohaustorius estuarius     

#### EDIT_3

"Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5"

##### Edits

- Use pub data
- Except: use UNI sigdiff

In [48]:
edits_3 = (edits[edits.unify_comment == "Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5"]
    .rename({"sampletypecode.uni": "sampletypecode", "species.uni": "species"}, axis=1))
edits_3.loc[:, 'stationid'] = edits_3.stationid.astype(str)
edits_3.loc[:, 'sampletypecode'] = edits_3.sampletypecode.str.upper()
edits_3 = edits_3.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
pub = (
    pub_2008
        .copy()
        .rename({
            'StationID': 'stationid', 
            'QABatch': 'toxbatch',
            'Species': 'species',
            'SampleType': 'sampletypecode'
        }, axis=1)
        .replace(
            to_replace=["EE", "MG", 'Result'], value=["Eohaustorius estuarius", "Mytilus galloprovincialis", "RESULT"]
        )
)
pub.loc[:, ['stationid']] = pub.stationid.astype(str)
pub = pub.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
uni = uni_2008.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
indexer = pub.index.intersection(edits_3.index).to_flat_index().tolist()
old_cols = ['Mean','N','StdDev','PctControl']
new_cols = ['mean','n','stddev','pctcontrol']
mapper = dict(zip(old_cols, new_cols))

u = uni.drop(new_cols, axis=1).join(pub[old_cols].rename(mapper, axis=1))
u.loc[indexer, ['unify_comment', 'unify_action']] = (
    "Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5",
    "EDIT"
)
EDIT_3 = u.loc[indexer]
EDIT_3

objectid  \
stationid toxbatch    sampletypecode species                            
6134      B08EE082008 RESULT         Eohaustorius estuarius      3219   
6156      B08EE082008 RESULT         Eohaustorius estuarius      3240   

                                                             surveyyear  \
stationid toxbatch    sampletypecode species                              
6134      B08EE082008 RESULT         Eohaustorius estuarius        2008   
6156      B08EE082008 RESULT         Eohaustorius estuarius        2008   

                                                                          lab  \
stationid toxbatch    sampletypecode species                                    
6134      B08EE082008 RESULT         Eohaustorius estuarius  Weston Solutions   
6156      B08EE082008 RESULT         Eohaustorius estuarius  Weston Solutions   

                                                            dilution  \
stationid toxbatch    sampletypecode species                           
6134      B08EE082008 RESULT         Eohaustorius estuarius     None   
6156      B08EE082008 RESULT         Eohaustorius estuarius     None   

                                                             fieldreplicate  \
stationid toxbatch    sampletypecode species                                  
6134      B08EE082008 RESULT         Eohaustorius estuarius               1   
6156      B08EE082008 RESULT         Eohaustorius estuarius               1   

                                                               pvalue  \
stationid toxbatch    sampletypecode species                            
6134      B08EE082008 RESULT         Eohaustorius estuarius   0.04156   
6156      B08EE082008 RESULT         Eohaustorius estuarius  0.041668   

                                                            control_mean  \
stationid toxbatch    sampletypecode species                               
6134      B08EE082008 RESULT         Eohaustorius estuarius         93.0   
6156      B08EE082008 RESULT         Eohaustorius estuarius         93.0   

                                                            coefficientvariance  \
stationid toxbatch    sampletypecode species                                      
6134      B08EE082008 RESULT         Eohaustorius estuarius            0.063689   
6156      B08EE082008 RESULT         Eohaustorius estuarius            0.097808   

                                                                  units  \
stationid toxbatch    sampletypecode species                              
6134      B08EE082008 RESULT         Eohaustorius estuarius  percentage   
6156      B08EE082008 RESULT         Eohaustorius estuarius  percentage   

                                                            qacode  ...  \
stationid toxbatch    sampletypecode species                        ...   
6134      B08EE082008 RESULT         Eohaustorius estuarius      A  ...   
6156      B08EE082008 RESULT         Eohaustorius estuarius      A  ...   

                                                                            endpoint  \
stationid toxbatch    sampletypecode species                                           
6134      B08EE082008 RESULT         Eohaustorius estuarius  10 day survival percent   
6156      B08EE082008 RESULT         Eohaustorius estuarius  10 day survival percent   

                                                            sqo_category_value_initial  \
stationid toxbatch    sampletypecode species                                             
6134      B08EE082008 RESULT         Eohaustorius estuarius                        2.0   
6156      B08EE082008 RESULT         Eohaustorius estuarius                        2.0   

                                                            Score sqocategory  \
stationid toxbatch    sampletypecode species                                    
6134      B08EE082008 RESULT         Eohaustorius estuarius   2.0        None   
6156      B08EE082008 RESULT         Eohaustor

#### EDIT_4

`Uni using control mean 93, should be 90.33. Pub sigdiff doesn't correspond properly to pval.`

Use published data except for P value and sigdiff


In [49]:
edits_4 = (edits[edits.unify_comment == "Uni using control mean 93, should be 90.33. Pub sigdiff doesn't correspond properly to pval."]
    .rename({"sampletypecode.uni": "sampletypecode", "species.uni": "species"}, axis=1))
edits_4.loc[:, 'stationid'] = edits_4.stationid.astype(str)
edits_4.loc[:, 'sampletypecode'] = edits_4.sampletypecode.str.upper()
edits_4 = edits_4.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
pub = (
    pub_2008
        .copy()
        .rename({
            'StationID': 'stationid', 
            'QABatch': 'toxbatch',
            'Species': 'species',
            'SampleType': 'sampletypecode'
        }, axis=1)
        .replace(
            to_replace=["EE", "MG", 'Result'], value=["Eohaustorius estuarius", "Mytilus galloprovincialis", "RESULT"]
        )
)
pub.loc[:, ['stationid']] = pub.stationid.astype(str)
pub = pub.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
uni = uni_2008.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
indexer = pub.index.intersection(edits_4.index).to_flat_index().tolist()
old_cols = ['Mean','N','StdDev','PctControl']
new_cols = ['mean','n','stddev','pctcontrol']
mapper = dict(zip(old_cols, new_cols))

u = uni.drop(new_cols, axis=1).join(pub[old_cols].rename(mapper, axis=1))
u.loc[indexer, ['unify_comment', 'unify_action']] = (
    "Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5",
    "EDIT"
)
EDIT_4 = u.loc[indexer]
EDIT_4

objectid  \
stationid toxbatch       sampletypecode species                            
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3288   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius      3294   

                                                                surveyyear  \
stationid toxbatch       sampletypecode species                              
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius        2008   

                                                                             lab  \
stationid toxbatch       sampletypecode species                                    
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Weston Solutions   

                                                               dilution  \
stationid toxbatch       sampletypecode species                           
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius     None   

                                                                fieldreplicate  \
stationid toxbatch       sampletypecode species                                  
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius               1   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius               1   

                                                                  pvalue  \
stationid toxbatch       sampletypecode species                            
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius  0.020106   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius  0.021951   

                                                               control_mean  \
stationid toxbatch       sampletypecode species                               
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius         93.0   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius         93.0   

                                                               coefficientvariance  \
stationid toxbatch       sampletypecode species                                      
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius            0.072044   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius            0.063689   

                                                                     units  \
stationid toxbatch       sampletypecode species                              
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius  percentage   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius  percentage   

                                                               qacode  ...  \
stationid toxbatch       sampletypecode species                        ...   
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius      A  ...   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius      A  ...   

                                                                               endpoint  \
stationid toxbatch       sampletypecode species                                           
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius  10 day survival percent   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius  10 day survival percent   

                                                               sqo_category_value_initial  \
stationid toxbatch       sampletypecode species                                             
6239      B08EELPLSELTJR RESULT         Eohaustorius estuarius                        2.0   
6244      B08EELPLSELTJR RESULT         Eohaustorius estuarius                        2.0   

                                                               Score  \
stationid toxbatch       sampletypecode species                        
6239

#### EDIT_5

Use Published values except for p-value and sigdiff

In [50]:
edits_5 = (edits[edits.unify_comment == "Pub has NSC for sigdiff, but P value below 0.05. Use UNI sigdiff"]
    .rename({"sampletypecode.uni": "sampletypecode", "species.uni": "species"}, axis=1))
edits_5.loc[:, 'stationid'] = edits_5.stationid.astype(str)
edits_5.loc[:, 'sampletypecode'] = edits_5.sampletypecode.str.upper()
edits_5 = edits_5.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
edits_5

unify_comment  \
stationid toxbatch       sampletypecode species                                                                     
6012      B08EELPLSELTJR RESULT         Eohaustorius estuarius  Pub has NSC for sigdiff, but P value below 0.0...   
6025      B08EE090908    RESULT         Eohaustorius estuarius  Pub has NSC for sigdiff, but P value below 0.0...   

                                                               unify_action  
stationid toxbatch       sampletypecode species                              
6012      B08EELPLSELTJR RESULT         Eohaustorius estuarius         EDIT  
6025      B08EE090908    RESULT         Eohaustorius estuarius         EDIT

In [51]:
pub = (
    pub_2008
        .copy()
        .rename({
            'StationID': 'stationid', 
            'QABatch': 'toxbatch',
            'Species': 'species',
            'SampleType': 'sampletypecode'
        }, axis=1)
        .replace(
            to_replace=["EE", "MG", 'Result'], value=["Eohaustorius estuarius", "Mytilus galloprovincialis", "RESULT"]
        )
)
pub.loc[:, ['stationid']] = pub.stationid.astype(str)
pub = pub.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
uni = uni_2008.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
indexer = pub.index.intersection(edits_5.index).to_flat_index().tolist()
old_cols = ['Mean','N','StdDev','PctControl']
new_cols = ['mean','n','stddev','pctcontrol']
mapper = dict(zip(old_cols, new_cols))

u = uni.drop(new_cols, axis=1).join(pub[old_cols].rename(mapper, axis=1))
u.loc[indexer, ['unify_comment', 'unify_action']] = (
    "Pub sigdiff doesn't correspond properly to pval. Uni uses CNEG mean of 93 instead of the correct 90.5",
    "EDIT"
)
EDIT_5 = u.loc[indexer]
EDIT_5[['sigeffect']]

sigeffect
stationid toxbatch       sampletypecode species                         
6012      B08EELPLSELTJR RESULT         Eohaustorius estuarius        SC
6025      B08EE090908    RESULT         Eohaustorius estuarius        SC

### DELETIONS

In [52]:
deletes[['unify_comment', 'unify_action']].value_counts()

unify_comment                                               unify_action
Don't publish QA samples                                    DELETE          48
All qa code X                                               DELETE          15
Not sure what these are and why they're in the comparison   DELETE           7
CNEG/QA samples only. Don't publish                         DELETE           3
Station SC12 doesn't exist in published Results. CNEG only  DELETE           1
Name: count, dtype: int64

In [53]:
uni = uni_2008.set_index(['stationid', 'toxbatch',  'sampletypecode', 'species'])
d = (deletes
    .rename({
        'sampletypecode.uni': 'sampletypecode',
        'species.uni': 'species'
    }, axis=1)
)
d.loc[:, 'stationid'] = d.stationid.astype(str)
d.loc[:, 'sampletypecode'] = d.sampletypecode.str.upper()
d = d.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
indexer = d.index.intersection(uni.index).to_flat_index().tolist()
indexer

[('0000', 'B08MG05', 'CNEG', 'Mytilus galloprovincialis'),
 ('0000', 'B08MG09', 'CNEG', 'Mytilus galloprovincialis'),
 ('0000', 'B08MGBL', 'CNEG', 'Mytilus galloprovincialis'),
 ('6113', 'B08MG09', 'RESULT', 'Mytilus galloprovincialis'),
 ('6115', 'B08MG09', 'RESULT', 'Mytilus galloprovincialis'),
 ('6145', 'B08MG05', 'RESULT', 'Mytilus galloprovincialis'),
 ('6148', 'B08MG05', 'RESULT', 'Mytilus galloprovincialis'),
 ('6165', 'B08MG05', 'RESULT', 'Mytilus galloprovincialis'),
 ('6171', 'B08MG05', 'RESULT', 'Mytilus galloprovincialis'),
 ('6179', 'B08MG05', 'RESULT', 'Mytilus galloprovincialis'),
 ('6250', 'B08MGBL', 'RESULT', 'Mytilus galloprovincialis'),
 ('6251', 'B08MGBL', 'RESULT', 'Mytilus galloprovincialis'),
 ('6252', 'B08MGBL', 'RESULT', 'Mytilus galloprovincialis'),
 ('6253', 'B08MGBL', 'RESULT', 'Mytilus galloprovincialis'),
 ('6264', 'B08MGBL', 'RESULT', 'Mytilus galloprovincialis')]

In [54]:
d[['unify_comment', 'unify_action']]

unify_comment  \
stationid toxbatch       sampletypecode species                                                                        
0000      B08MG05        CNEG           Mytilus galloprovincialis                                      All qa code X   
          B08MG09        CNEG           Mytilus galloprovincialis                                      All qa code X   
          B08MGBL        CNEG           Mytilus galloprovincialis                                      All qa code X   
6113      B08MG09        RESULT         Mytilus galloprovincialis                                      All qa code X   
6115      B08MG09        RESULT         Mytilus galloprovincialis                                      All qa code X   
...                                                                                                              ...   
None      B08EE090508    NaN            Eohaustorius estuarius     Not sure what these are and why they're in the...   
          B08EE090908    NaN            Eohaustorius estuarius     Not sure what these are and why they're in the...   
          B08EELPLSELTJR NaN            Eohaustorius estuarius     Not sure what these are and why they're in the...   
          B08MGSPLIT     NaN            Mytilus galloprovincialis  Not sure what these are and why they're in the...   
SC12      B08EESEL6242   NaN            NaN                        Station SC12 doesn't exist in published Result...   

                                                                  unify_action  
stationid toxbatch       sampletypecode species                                 
0000      B08MG05        CNEG           Mytilus galloprovincialis       DELETE  
          B08MG09        CNEG           Mytilus galloprovincialis       DELETE  
          B08MGBL        CNEG           Mytilus galloprovincialis       DELETE  
6113      B08MG09        RESULT         Mytilus galloprovincialis       DELETE  
6115      B08MG09        RESULT         Mytilus galloprovincialis       DELETE  
...                                                                        ...  
None      B08EE090508    NaN            Eohaustorius estuarius          DELETE  
          B08EE090908    NaN            Eohaustorius estuarius          DELETE  
          B08EELPLSELTJR NaN            Eohaustorius estuarius          DELETE  
          B08MGSPLIT     NaN            Mytilus galloprovincialis       DELETE  
SC12      B08EESEL6242   NaN            NaN                             DELETE  

[74 rows x 2 columns]

In [55]:
DELETE_1 = uni.join(d[['unify_comment', 'unify_action']]).loc[indexer]
DELETE_1

objectid  \
stationid toxbatch sampletypecode species                               
0000      B08MG05  CNEG           Mytilus galloprovincialis      3101   
          B08MG09  CNEG           Mytilus galloprovincialis      3105   
          B08MGBL  CNEG           Mytilus galloprovincialis      3115   
6113      B08MG09  RESULT         Mytilus galloprovincialis      3198   
6115      B08MG09  RESULT         Mytilus galloprovincialis      3200   
6145      B08MG05  RESULT         Mytilus galloprovincialis      3227   
6148      B08MG05  RESULT         Mytilus galloprovincialis      3229   
6165      B08MG05  RESULT         Mytilus galloprovincialis      3246   
6171      B08MG05  RESULT         Mytilus galloprovincialis      3249   
6179      B08MG05  RESULT         Mytilus galloprovincialis      3257   
6250      B08MGBL  RESULT         Mytilus galloprovincialis      3299   
6251      B08MGBL  RESULT         Mytilus galloprovincialis      3301   
6252      B08MGBL  RESULT         Mytilus galloprovincialis      3303   
6253      B08MGBL  RESULT         Mytilus galloprovincialis      3305   
6264      B08MGBL  RESULT         Mytilus galloprovincialis      3307   

                                                             surveyyear  \
stationid toxbatch sampletypecode species                                 
0000      B08MG05  CNEG           Mytilus galloprovincialis        2008   
          B08MG09  CNEG           Mytilus galloprovincialis        2008   
          B08MGBL  CNEG           Mytilus galloprovincialis        2008   
6113      B08MG09  RESULT         Mytilus galloprovincialis        2008   
6115      B08MG09  RESULT         Mytilus galloprovincialis        2008   
6145      B08MG05  RESULT         Mytilus galloprovincialis        2008   
6148      B08MG05  RESULT         Mytilus galloprovincialis        2008   
6165      B08MG05  RESULT         Mytilus galloprovincialis        2008   
6171      B08MG05  RESULT         Mytilus galloprovincialis        2008   
6179      B08MG05  RESULT         Mytilus galloprovincialis        2008   
6250      B08MGBL  RESULT         Mytilus galloprovincialis        2008   
6251      B08MGBL  RESULT         Mytilus galloprovincialis        2008   
6252      B08MGBL  RESULT         Mytilus galloprovincialis        2008   
6253      B08MGBL  RESULT         Mytilus galloprovincialis        2008   
6264      B08MGBL  RESULT         Mytilus galloprovincialis        2008   

                                                                          lab  \
stationid toxbatch sampletypecode species                                       
0000      B08MG05  CNEG           Mytilus galloprovincialis  Weston Solutions   
          B08MG09  CNEG           Mytilus galloprovincialis  Weston Solutions   
          B08MGBL  CNEG           Mytilus galloprovincialis  Weston Solutions   
6113      B08MG09  RESULT         Mytilus galloprovincialis  Weston Solutions   
6115      B08MG09  RESULT         Mytilus galloprovincialis  Weston Solutions   
6145      B08MG05  RESULT         Mytilus galloprovincialis  Weston Solutions   
6148      B08MG05  RESULT         Mytilus galloprovincialis  Weston Solutions   
6165      B08MG05  RESULT         Mytilus galloprovincialis  Weston Solutions   
6171      B08MG05  RESULT         Mytilus galloprovincialis  Weston Solutions   
6179      B08MG05  RESULT         Mytilus galloprovincialis  Weston Solutions   
6250      B08MGBL  RESULT         Mytilus galloprovincialis  Weston Solutions   
6251      B08MGBL  RESULT         Mytilus galloprovincialis  Weston Solutions   
6252      B08MGBL  RESULT         Mytilus galloprovincialis  Weston Solutions   
6253      B08MGBL  RESULT         Mytilus galloprovincialis  Weston Solutions   
6264      B08MGBL  RESULT         Mytilus galloprovincialis  Weston Solutions   

                                                            dilution  \
stationid toxbatch sampletypecode species                              
0000      B08MG05  CN

### INTEGRATE

In [56]:
all_changes = [EDIT_1, EDIT_2, EDIT_3, EDIT_4, EDIT_5, DELETE_1]
ch = pd.concat(all_changes).replace(np.nan, None)
ch

/var/folders/5b/h4bvk5pj1l569v2_1w51mfx00000gn/T/ipykernel_3555/2984045302.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ch = pd.concat(all_changes).replace(np.nan, None)


objectid  \
stationid toxbatch        sampletypecode species                               
6363      GC_B08MG3_S_TOX RESULT         Mytilus galloprovincialis      2989   
6375      GC_B08EE6_S_TOX RESULT         Eohaustorius estuarius         2992   
6068      B08EE090908     RESULT         Eohaustorius estuarius         3169   
6080      B08MG12         RESULT         Mytilus galloprovincialis      3179   
6094      B08EE090508     RESULT         Eohaustorius estuarius         3193   
6181      B08EESDR        RESULT         Eohaustorius estuarius         3260   
6189      B08EESDR        RESULT         Eohaustorius estuarius         3262   
6192      B08EESDR        RESULT         Eohaustorius estuarius         3264   
6197      B08EESDR        RESULT         Eohaustorius estuarius         3266   
6200      B08EESDR        RESULT         Eohaustorius estuarius         3268   
6288      B08EE082608     RESULT         Eohaustorius estuarius         3318   
6303      B08MG091008     RESULT         Mytilus galloprovincialis      3325   
6308      B08MG091008     RESULT         Mytilus galloprovincialis      3327   
6311      B08MG091008     RESULT         Mytilus galloprovincialis      3329   
6317      B08MG091008     RESULT         Mytilus galloprovincialis      3333   
6327      B08EE082608     RESULT         Eohaustorius estuarius         3338   
6328      B08EE082608     RESULT         Eohaustorius estuarius         3340   
6001      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3122   
6004      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3124   
6009      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3126   
6010      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3128   
6228      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3278   
6229      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3280   
6230      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3282   
6232      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3284   
6236      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3286   
6243      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3292   
6245      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3296   
6134      B08EE082008     RESULT         Eohaustorius estuarius         3219   
6156      B08EE082008     RESULT         Eohaustorius estuarius         3240   
6239      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3288   
6244      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3294   
6012      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3130   
6025      B08EE090908     RESULT         Eohaustorius estuarius         3136   
0000      B08MG05         CNEG           Mytilus galloprovincialis      3101   
          B08MG09         CNEG           Mytilus galloprovincialis      3105   
          B08MGBL         CNEG           Mytilus galloprovincialis      3115   
6113      B08MG09         RESULT         Mytilus galloprovincialis      3198   
6115      B08MG09         RESULT         Mytilus galloprovincialis      3200   
6145      B08MG05         RESULT         Mytilus galloprovincialis      3227   
6148      B08MG05         RESULT         Mytilus galloprovincialis      3229   
6165      B08MG05         RESULT         Mytilus galloprovincialis      3246   
6171      B08MG05         RESULT         Mytilus galloprovincialis      3249   
6179      B08MG05         RESULT         Mytilus galloprovincialis      3257   
6250      B08MGBL         RESULT         Mytilus galloprovincialis      3299   
6251      B08MGBL         RESULT         Mytilus galloprovincialis      3301   
6252      B08MGBL         RESULT         Mytilus galloprovincialis      3303   
6253      B08MGBL         RESULT         Mytilus galloprovincialis      3305   
6264      B08MGBL         RESULT         Mytilus galloprovincialis  

In [57]:
uni = uni_2008.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
uni[['unify_comment', 'unify_action']] = None, None
uni

objectid  \
stationid toxbatch       sampletypecode species                               
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius         2866   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius         2867   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius         2868   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius         2869   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius         2870   
...                                                                     ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis      3347   
6660      B08EE090208    RESULT         Eohaustorius estuarius         3348   
          B08MG13        RESULT         Mytilus galloprovincialis      3349   
6661      B08EE090208    RESULT         Eohaustorius estuarius         3350   
          B08MG12        RESULT         Mytilus galloprovincialis      3351   

                                                                   surveyyear  \
stationid toxbatch       sampletypecode species                                 
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius           2008   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius           2008   
...                                                                       ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis        2008   
6660      B08EE090208    RESULT         Eohaustorius estuarius           2008   
          B08MG13        RESULT         Mytilus galloprovincialis        2008   
6661      B08EE090208    RESULT         Eohaustorius estuarius           2008   
          B08MG12        RESULT         Mytilus galloprovincialis        2008   

                                                                                                            lab  \
stationid toxbatch       sampletypecode species                                                                   
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
...                                                                                                         ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis                              Weston Solutions   
6660      B08EE090208    RESULT         Eohaustorius estuarius                                 Weston Solutions   
          B08MG13        RESULT         Mytilus galloprovincialis                              Weston Solutions   
6661      B08EE090208    RESULT         Eohaustorius estuarius                                 Weston Solutions   
          B08MG12        RESULT         Mytilus galloprovincialis                              Weston Solutions   

                                                                  dilution  \
stationid toxbatch       sampletypecode species                              
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius        None   
          EOHT 9.12.2

In [58]:
uni.index.intersection(ch.index).to_flat_index().tolist()
ch

objectid  \
stationid toxbatch        sampletypecode species                               
6363      GC_B08MG3_S_TOX RESULT         Mytilus galloprovincialis      2989   
6375      GC_B08EE6_S_TOX RESULT         Eohaustorius estuarius         2992   
6068      B08EE090908     RESULT         Eohaustorius estuarius         3169   
6080      B08MG12         RESULT         Mytilus galloprovincialis      3179   
6094      B08EE090508     RESULT         Eohaustorius estuarius         3193   
6181      B08EESDR        RESULT         Eohaustorius estuarius         3260   
6189      B08EESDR        RESULT         Eohaustorius estuarius         3262   
6192      B08EESDR        RESULT         Eohaustorius estuarius         3264   
6197      B08EESDR        RESULT         Eohaustorius estuarius         3266   
6200      B08EESDR        RESULT         Eohaustorius estuarius         3268   
6288      B08EE082608     RESULT         Eohaustorius estuarius         3318   
6303      B08MG091008     RESULT         Mytilus galloprovincialis      3325   
6308      B08MG091008     RESULT         Mytilus galloprovincialis      3327   
6311      B08MG091008     RESULT         Mytilus galloprovincialis      3329   
6317      B08MG091008     RESULT         Mytilus galloprovincialis      3333   
6327      B08EE082608     RESULT         Eohaustorius estuarius         3338   
6328      B08EE082608     RESULT         Eohaustorius estuarius         3340   
6001      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3122   
6004      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3124   
6009      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3126   
6010      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3128   
6228      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3278   
6229      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3280   
6230      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3282   
6232      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3284   
6236      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3286   
6243      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3292   
6245      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3296   
6134      B08EE082008     RESULT         Eohaustorius estuarius         3219   
6156      B08EE082008     RESULT         Eohaustorius estuarius         3240   
6239      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3288   
6244      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3294   
6012      B08EELPLSELTJR  RESULT         Eohaustorius estuarius         3130   
6025      B08EE090908     RESULT         Eohaustorius estuarius         3136   
0000      B08MG05         CNEG           Mytilus galloprovincialis      3101   
          B08MG09         CNEG           Mytilus galloprovincialis      3105   
          B08MGBL         CNEG           Mytilus galloprovincialis      3115   
6113      B08MG09         RESULT         Mytilus galloprovincialis      3198   
6115      B08MG09         RESULT         Mytilus galloprovincialis      3200   
6145      B08MG05         RESULT         Mytilus galloprovincialis      3227   
6148      B08MG05         RESULT         Mytilus galloprovincialis      3229   
6165      B08MG05         RESULT         Mytilus galloprovincialis      3246   
6171      B08MG05         RESULT         Mytilus galloprovincialis      3249   
6179      B08MG05         RESULT         Mytilus galloprovincialis      3257   
6250      B08MGBL         RESULT         Mytilus galloprovincialis      3299   
6251      B08MGBL         RESULT         Mytilus galloprovincialis      3301   
6252      B08MGBL         RESULT         Mytilus galloprovincialis      3303   
6253      B08MGBL         RESULT         Mytilus galloprovincialis      3305   
6264      B08MGBL         RESULT         Mytilus galloprovincialis  

In [59]:
uni.loc[indexer] = ch
unify_2008_correct = uni.copy()

In [60]:
unify_2008_correct

objectid  \
stationid toxbatch       sampletypecode species                               
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius         2866   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius         2867   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius         2868   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius         2869   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius         2870   
...                                                                     ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis      3347   
6660      B08EE090208    RESULT         Eohaustorius estuarius         3348   
          B08MG13        RESULT         Mytilus galloprovincialis      3349   
6661      B08EE090208    RESULT         Eohaustorius estuarius         3350   
          B08MG12        RESULT         Mytilus galloprovincialis      3351   

                                                                   surveyyear  \
stationid toxbatch       sampletypecode species                                 
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius           2008   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius           2008   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius           2008   
...                                                                       ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis        2008   
6660      B08EE090208    RESULT         Eohaustorius estuarius           2008   
          B08MG13        RESULT         Mytilus galloprovincialis        2008   
6661      B08EE090208    RESULT         Eohaustorius estuarius           2008   
          B08MG12        RESULT         Mytilus galloprovincialis        2008   

                                                                                                            lab  \
stationid toxbatch       sampletypecode species                                                                   
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
          EOHT 9.12.2008 CNEG           Eohaustorius estuarius     Aquatic Bioassay and Consulting Laboratories   
...                                                                                                         ...   
6659      B08MG14        RESULT         Mytilus galloprovincialis                              Weston Solutions   
6660      B08EE090208    RESULT         Eohaustorius estuarius                                 Weston Solutions   
          B08MG13        RESULT         Mytilus galloprovincialis                              Weston Solutions   
6661      B08EE090208    RESULT         Eohaustorius estuarius                                 Weston Solutions   
          B08MG12        RESULT         Mytilus galloprovincialis                              Weston Solutions   

                                                                  dilution  \
stationid toxbatch       sampletypecode species                              
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 7.31.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 8.11.2008 CNEG           Eohaustorius estuarius        None   
          EOHT 9.1.2008  CNEG           Eohaustorius estuarius        None   
          EOHT 9.12.2

## Specs for 2003

In [61]:
uni_2003 = df[df["surveyyear"] == 2003]
uni_2003.loc[:, 'stationid'] = uni_2003.stationid.astype(str)
pub_2003 = pd.read_excel("compare_2025.08.21/2003/tblToxicitySummaryResults.xlsx")
com_2003 = pd.read_excel("compare_2025.08.21/2003/compare-2003.xlsx")
com_2003 = (
    com_2003
        .replace(np.nan, None)
        .rename({
            "COMMENT": "unify_comment",
            "ACTION": "unify_action"
        }, axis=1)
)
deletes_03 = com_2003[com_2003.unify_action == "DELETE"]
edits_03 = com_2003[com_2003.unify_action == "EDIT"]

#### DELETES

In [62]:
deletes_03[deletes_03.unify_comment == 'No Result sample types in results data']

unify_comment unify_action  surveyyear  \
273  No Result sample types in results data       DELETE        2003   
274  No Result sample types in results data       DELETE        2003   
275  No Result sample types in results data       DELETE        2003   
276  No Result sample types in results data       DELETE        2003   
277  No Result sample types in results data       DELETE        2003   
278  No Result sample types in results data       DELETE        2003   
279  No Result sample types in results data       DELETE        2003   

    stationid toxbatch Category.pub Category.uni  Category.zcomp  \
273      0000   OCSD06         None         None           False   
274      0000   OCSD06         None         None           False   
275      0000   OCSD06         None         None           False   
276      0000   OCSD06         None         None           False   
277      0000   OCSD06         None         None           False   
278      0000   OCSD06         None         None           False   
279      0000   OCSD06         None         None           False   

    sampletypecode.pub sampletypecode.uni  ... species.pub  \
273               CNEG               CNEG  ...          EE   
274               RFCD               CNEG  ...          EE   
275               RFCD               CNEG  ...          EE   
276               RFCD               CNEG  ...          EE   
277               RFCD               CNEG  ...          EE   
278               RFCD               CNEG  ...          EE   
279               RFCD               CNEG  ...          EE   

                species.uni sqo_category_value_initial Standard Deviation.pub  \
273  Eohaustorius estuarius                       None                   6.12   
274  Eohaustorius estuarius                       None                   5.77   
275  Eohaustorius estuarius                       None                   10.0   
276  Eohaustorius estuarius                       None                   5.77   
277  Eohaustorius estuarius                       None                   20.0   
278  Eohaustorius estuarius                       None                   10.0   
279  Eohaustorius estuarius                       None                   5.77   

    Standard Deviation.uni COMP.4 StatisticalTest treatment    units    Units  
273               6.123724   None      Not tested      None  Percent  PERCENT  
274               6.123724   None      Not tested      None  Percent  PERCENT  
275               6.123724   None      Not tested      None  Percent  PERCENT  
276               6.123724   None      Not tested      None  Percent  PERCENT  
277               6.123724   None      Not tested      None  Percent  PERCENT  
278               6.123724   None      Not tested      None  Percent  PERCENT  
279               6.123724   None      Not tested      None  Percent  PERCENT  

[7 rows x 50 columns]

In [63]:
deletes_03[['unify_comment', 'unify_action']].value_counts()

unify_comment                           unify_action
Not Result or CNEG                      DELETE          252
No Result sample types in results data  DELETE            7
Name: count, dtype: int64

In [64]:
d = (
    deletes_03
        .rename({
            'sampletypecode.uni': 'sampletypecode',
            'species.uni': 'species'
        }, axis=1)
        .replace(np.nan, None)
)
d.loc[:, 'stationid'] = d.stationid.astype(str)
d.loc[:, 'sampletypecode'] = d.sampletypecode.str.upper()
d = d.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
d = d[['unify_comment', 'unify_action']]
u = uni_2003.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
DELETE = u.join(d, how='inner')
DELETE

objectid  \
stationid toxbatch sampletypecode species                            
0000      OCSD06   CNEG           Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   
                                  Eohaustorius estuarius      2849   

                                                          surveyyear  \
stationid toxbatch sampletypecode species                              
0000      OCSD06   CNEG           Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   
                                  Eohaustorius estuarius        2003   

                                                                                                lab  \
stationid toxbatch sampletypecode species                                                             
0000      OCSD06   CNEG           Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   
                                  Eohaustorius estuarius  Orange County Sanitation Districts (OCSD)   

                                                         dilution  \
stationid toxbatch sampletypecode species                           
0000      OCSD06   CNEG           Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   
                                  Eohaustorius estuarius     None   

                                                          fieldreplicate  \
stationid toxbatch sampletypecode species                                  
0000      OCSD06   CNEG           Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   
                                  Eohaustorius estuarius               1   

                                                         pvalue  mean  \
stationid toxbatch sampletypecode species                               
0000      OCSD06   CNEG           Eohaustorius estuarius    0.5  95.0   
                                  Eohaustorius estuarius    0.5  95.0   
                                  Eohaustorius estuarius    0.5  95.0   
                                  Eohaustorius estuarius    0.5  95.0   
                                  Eohaustorius estuarius    0.5  95.0   
                                

#### EDITS

1. Get the published data
2. Get the edits
3. Narrow down the published data to that which is to be edited
4. Get the data to be saved as well as the unified comment and action
5. Join the published edits onto the unified summary data

In [65]:
edits_03[['unify_comment', 'unify_action']].value_counts()

unify_comment                                                             unify_action
Pub: Sigdiff doesn't correspond with p value. Use pub except for sigdiff  EDIT            34
Name: count, dtype: int64

In [66]:
old_cols = ['StationID', 'QABatch', 'SampleType', 'SpeciesCode']
key_cols = ['stationid', 'toxbatch', 'sampletypecode', 'species']
mapper = dict(zip(old_cols, key_cols))
p = (
    pub_2003
        .copy()
        .rename(mapper, axis=1)
        .replace(
            to_replace=["EE", "MG", 'Result'], value=["Eohaustorius estuarius", "Mytilus galloprovincialis", "RESULT"]
        )
)
p.loc[:, 'stationid'] = p.stationid.astype(str)
print(p.sampletypecode.value_counts())
p = p.set_index(key_cols)
old_cols = ['Mean','N','StdDev','PctControl']
new_cols = ['mean','n','stddev','pctcontrol']
mapper = dict(zip(old_cols, new_cols))
p = p.rename(mapper, axis=1)[new_cols]
p

sampletypecode
RESULT    229
RFCD      132
RFNH3     109
CNEG       22
QA          9
Name: count, dtype: int64


mean  n  stddev  \
stationid toxbatch sampletypecode species                                    
0         1        CNEG           Eohaustorius estuarius  100.0  5    0.00   
          10       CNEG           Eohaustorius estuarius   99.0  5    2.23   
          4        CNEG           Eohaustorius estuarius  100.0  5    0.00   
          6        CNEG           Eohaustorius estuarius  100.0  5    0.00   
          8        CNEG           Eohaustorius estuarius  100.0  5    0.00   
...                                                         ... ..     ...   
SPLT1     Batch 3  QA             Eohaustorius estuarius   45.0  5   16.95   
          OCSD01   QA             Eohaustorius estuarius   64.0  5   12.94   
SPLT2     6        QA             Eohaustorius estuarius   27.0  5    8.36   
          Batch 11 QA             Eohaustorius estuarius   43.0  5    9.08   
          OCSD04   QA             Eohaustorius estuarius   10.0  5    9.35   

                                                          pctcontrol  
stationid toxbatch sampletypecode species                             
0         1        CNEG           Eohaustorius estuarius      100.00  
          10       CNEG           Eohaustorius estuarius      100.00  
          4        CNEG           Eohaustorius estuarius      100.00  
          6        CNEG           Eohaustorius estuarius      100.00  
          8        CNEG           Eohaustorius estuarius      100.00  
...                                                              ...  
SPLT1     Batch 3  QA             Eohaustorius estuarius       49.45  
          OCSD01   QA             Eohaustorius estuarius       66.66  
SPLT2     6        QA             Eohaustorius estuarius       27.00  
          Batch 11 QA             Eohaustorius estuarius       48.04  
          OCSD04   QA             Eohaustorius estuarius       10.52  

[501 rows x 4 columns]

In [67]:
e = (
    edits_03
        .rename({
            'sampletypecode.uni': 'sampletypecode',
            'species.uni': 'species'
        }, axis=1)
        .replace(np.nan, None)
)
e.loc[:, 'stationid'] = e.stationid.astype(str)
e.loc[:, 'sampletypecode'] = e.sampletypecode.str.upper()
old_cols = ['Mean','N','StdDev','PctControl']
new_cols = ['mean','n','stddev','pctcontrol']
mapper = dict(zip(old_cols, new_cols))
e.rename(mapper)
e = e.set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
e = e[['unify_comment', 'unify_action']]
indexer = e.index.intersection(p.index).to_flat_index().tolist()
e = p.loc[indexer].join(e)
u = uni_2003.copy()
u.loc[:, 'stationid'] = u.stationid.astype(str)
u.loc[:, 'sampletypecode'] = u.sampletypecode.str.upper()
key_cols = ['stationid', 'toxbatch', 'sampletypecode', 'species']
u = u.set_index(key_cols)
EDITS = u.drop(new_cols, axis=1).join(e, how='inner')

#### INTEGRATE

In [68]:
# ### MANUAL CORRECTIONS TO DELETIONS ###

# DELETE = pd.DataFrame({
#     'stationid': ['0000'],
#     'toxbatch': ['OCSD06'],
#     'sampletypecode': ['CNEG'],
#     'species': ['Eohaustorius estuarius'],
#     'unify_comment': ['No Result sample types in results data'],
#     'unify_action': ['DELETE']
# })
# key_cols = ['stationid', 'toxbatch', 'sampletypecode', 'species']
# DELETE = DELETE.set_index(key_cols)
DELETE_INDEX = ('0000', 'OCSD06', 'CNEG', 'Eohaustorius estuarius')
comment, action = 'No Result sample types in results data', 'DELETE'

In [69]:
all_ch = [EDITS]
all_ch = pd.concat(all_ch)
all_ch = all_ch.replace(np.nan, None)
u = uni_2003.copy()
u.loc[:, 'stationid'] = u.stationid.astype(str)
u.loc[:, 'sampletypecode'] = u.sampletypecode.str.upper()
key_cols = ['stationid', 'toxbatch', 'sampletypecode', 'species']
u = u.set_index(key_cols)
u[['unify_comment','unify_action']] = None, None
indexer = all_ch.index.intersection(u.index).to_flat_index().tolist()
indexer
u.loc[indexer] = all_ch
u.loc[[DELETE_INDEX], ['unify_comment', 'unify_action']] = comment, action
unify_2003_correct = u
unify_2003_correct

objectid  \
stationid toxbatch sampletypecode species                            
0000      1        CNEG           Eohaustorius estuarius      2615   
          10       CNEG           Eohaustorius estuarius      2616   
          4        CNEG           Eohaustorius estuarius      2617   
          6        CNEG           Eohaustorius estuarius      2618   
          8        CNEG           Eohaustorius estuarius      2619   
...                                                            ...   
4329      OCSD01   RESULT         Eohaustorius estuarius      2861   
4423      OCSD04   RESULT         Eohaustorius estuarius      2862   
BRI-08    OCSD01   RESULT         Eohaustorius estuarius      2863   
BRI-09    OCSD01   RESULT         Eohaustorius estuarius      2864   
BRI-10    OCSD01   RESULT         Eohaustorius estuarius      2865   

                                                          surveyyear  \
stationid toxbatch sampletypecode species                              
0000      1        CNEG           Eohaustorius estuarius        2003   
          10       CNEG           Eohaustorius estuarius        2003   
          4        CNEG           Eohaustorius estuarius        2003   
          6        CNEG           Eohaustorius estuarius        2003   
          8        CNEG           Eohaustorius estuarius        2003   
...                                                              ...   
4329      OCSD01   RESULT         Eohaustorius estuarius        2003   
4423      OCSD04   RESULT         Eohaustorius estuarius        2003   
BRI-08    OCSD01   RESULT         Eohaustorius estuarius        2003   
BRI-09    OCSD01   RESULT         Eohaustorius estuarius        2003   
BRI-10    OCSD01   RESULT         Eohaustorius estuarius        2003   

                                                                                                   lab  \
stationid toxbatch sampletypecode species                                                                
0000      1        CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   
          10       CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   
          4        CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   
          6        CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   
          8        CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   
...                                                                                                ...   
4329      OCSD01   RESULT         Eohaustorius estuarius     Orange County Sanitation Districts (OCSD)   
4423      OCSD04   RESULT         Eohaustorius estuarius     Orange County Sanitation Districts (OCSD)   
BRI-08    OCSD01   RESULT         Eohaustorius estuarius     Orange County Sanitation Districts (OCSD)   
BRI-09    OCSD01   RESULT         Eohaustorius estuarius     Orange County Sanitation Districts (OCSD)   
BRI-10    OCSD01   RESULT         Eohaustorius estuarius     Orange County Sanitation Districts (OCSD)   

                                                         dilution  \
stationid toxbatch sampletypecode species                           
0000      1        CNEG           Eohaustorius estuarius     None   
          10       CNEG           Eohaustorius estuarius     None   
          4        CNEG           Eohaustorius estuarius     None   
          6        CNEG           Eohaustorius estuarius     None   
          8        CNEG           Eohaustorius estuarius     None   
...                                                           ...   
4329      OCSD01   RESULT         Eohaustorius estuarius     None   
4423      OCSD04   RESULT         Eohaustorius estuarius     None   
BRI-08    OCSD01   RESULT         Eohaustorius estuarius     None   
BRI-09    OCSD01   RESULT         Eohaustorius estuarius     None   
BRI

# INTEGRATE ALL YEARS

In [70]:
unify_2018_correct

surveyyear                                      lab  stationid  \
0          2018           AMEC, Foster, & Wheeler / WOOD       0000   
1          2018           AMEC, Foster, & Wheeler / WOOD       0000   
2          2018           AMEC, Foster, & Wheeler / WOOD       0000   
3          2018           AMEC, Foster, & Wheeler / WOOD       0000   
4          2018           AMEC, Foster, & Wheeler / WOOD       0000   
..          ...                                      ...        ...   
535        2018  Space and Naval Warfare Systems Command  B18-10138   
536        2018  Space and Naval Warfare Systems Command  B18-10447   
537        2018  Space and Naval Warfare Systems Command  B18-10447   
538        2018  Space and Naval Warfare Systems Command  B18-10465   
539        2018  Space and Naval Warfare Systems Command  B18-10465   

                            toxbatch                    species dilution  \
0     18-07-003 to-006; -011 to -014     Eohaustorius estuarius     None   
1    18-07-007 to -010; -015 to -018  Mytilus galloprovincialis     None   
2                  18-07-019 to -027     Eohaustorius estuarius     None   
3                  18-07-028 to -036  Mytilus galloprovincialis     None   
4                  18-07-053 to -065     Eohaustorius estuarius     None   
..                               ...                        ...      ...   
535                      SSC-2018-MG  Mytilus galloprovincialis     None   
536                     SSC-2018-EOH     Eohaustorius estuarius     None   
537                      SSC-2018-MG  Mytilus galloprovincialis     None   
538                     SSC-2018-EOH     Eohaustorius estuarius     None   
539                      SSC-2018-MG  Mytilus galloprovincialis     None   

     fieldreplicate sampletypecode    pvalue       mean  ...       units  \
0                 1           CNEG       0.5       97.0  ...  percentage   
1                 1           CNEG       0.5      91.14  ...  percentage   
2                 1           CNEG       0.5       95.0  ...  percentage   
3                 1           CNEG       0.5      92.44  ...  percentage   
4                 1           CNEG       0.5       99.0  ...  percentage   
..              ...            ...       ...        ...  ...         ...   
535               1         Result  0.159738  91.310901  ...  percentage   
536               1         Result  0.121438       97.0  ...  percentage   
537               1         Result  0.466088  94.039164  ...  percentage   
538               1         Result  0.121438       97.0  ...  percentage   
539               1         Result  0.420482  93.268608  ...  percentage   

    qacode treatment comments                    matrix sigeffect  \
0        A      None     None            Whole Sediment       NSC   
1        A      None     None  Sediment Water Interface       NSC   
2        A      None     None            Whole Sediment       NSC   
3        A      None     None  Sediment Water Interface       NSC   
4        A      None     None            Whole Sediment       NSC   
..     ...       ...      ...                       ...       ...   
535      A      None     None  Sediment Water Interface       NSC   
536      A      None     None            Whole Sediment       NSC   
537      A      None     None  Sediment Water Interface       NSC   
538      A      None     None            Whole Sediment       NSC   
539      A      None     None  Sediment Water Interface       NSC   

                    endpoint sqocategory  \
0    10 day survival percent        None   
1       Percent normal-alive        None   
2    10 day survival percent        None   
3       Percent normal-alive        None   
4    10 day survival percent        None   
..                       ...         ...   
535     Percent normal-alive    Nontoxic   
536  10 day survival percent    Nontoxic   
537     Percent normal-alive    Nontoxic   
538  10 day survival percent    Nontoxic   
539     Perce

In [71]:
key_cols = ['stationid', 'toxbatch', 'sampletypecode', 'species']

unify_2003_correct_ = unify_2003_correct.drop(['objectid'], axis=1)
unify_2008_correct_ = unify_2008_correct.drop(['objectid'], axis=1)
unify_2013_correct_ = unify_2013_correct.drop(['objectid'], axis=1).set_index(key_cols)
unify_2018_correct_ = unify_2018_correct.drop([], axis=1).set_index(key_cols)
unify_2023_correct_ = unify_2023_correct.drop([], axis=1).set_index(key_cols)

In [72]:
unify_1994_correct_ = df[df["surveyyear"].isin([1994])].drop(['objectid'], axis=1).set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
unify_1998_correct_ = df[df["surveyyear"].isin([1998])].drop(['objectid'], axis=1).set_index(['stationid', 'toxbatch', 'sampletypecode', 'species'])
len(unify_1994_correct_), len(unify_1998_correct_), len(unify_2003_correct_), len(unify_2008_correct_), len(unify_2013_correct_), len(unify_2018_correct_), len(unify_2023_correct_)

(342, 2272, 251, 486, 487, 540, 528)

In [73]:
unify_1994_correct_.head(1)

surveyyear  \
stationid toxbatch sampletypecode species                        
0016      940939   Result         Ampelisca abdita        1994   

                                                                                         lab  \
stationid toxbatch sampletypecode species                                                      
0016      940939   Result         Ampelisca abdita  Science Applications International Corp.   

                                                   dilution  fieldreplicate  \
stationid toxbatch sampletypecode species                                     
0016      940939   Result         Ampelisca abdita     None               1   

                                                     pvalue  mean  \
stationid toxbatch sampletypecode species                           
0016      940939   Result         Ampelisca abdita  0.08658  90.0   

                                                   control_mean pctcontrol  \
stationid toxbatch sampletypecode species                                    
0016      940939   Result         Ampelisca abdita         97.0  92.783505   

                                                      stddev  \
stationid toxbatch sampletypecode species                      
0016      940939   Result         Ampelisca abdita  9.354143   

                                                   coefficientvariance  ...  \
stationid toxbatch sampletypecode species                               ...   
0016      940939   Result         Ampelisca abdita            0.103935  ...   

                                                         units qacode  \
stationid toxbatch sampletypecode species                               
0016      940939   Result         Ampelisca abdita  percentage      A   

                                                   treatment comments  \
stationid toxbatch sampletypecode species                               
0016      940939   Result         Ampelisca abdita      None     None   

                                                            matrix sigeffect  \
stationid toxbatch sampletypecode species                                      
0016      940939   Result         Ampelisca abdita  Whole Sediment       NSC   

                                                                   endpoint  \
stationid toxbatch sampletypecode species                                     
0016      940939   Result         Ampelisca abdita  10 day survival percent   

                                                   sqo_category_value_initial  \
stationid toxbatch sampletypecode species                                       
0016      940939   Result         Ampelisca abdita                       None   

                                                   Score sqocategory  
stationid toxbatch sampletypecode species                             
0016      940939   Result         Ampelisca abdita  None        None  

[1 rows x 21 columns]

In [74]:
unify_1998_correct_.head(1)

surveyyear  \
stationid toxbatch sampletypecode species                              
0000      72798    CNEG           Eohaustorius estuarius        1998   

                                                                                      lab  \
stationid toxbatch sampletypecode species                                                   
0000      72798    CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting   

                                                         dilution  \
stationid toxbatch sampletypecode species                           
0000      72798    CNEG           Eohaustorius estuarius     None   

                                                          fieldreplicate  \
stationid toxbatch sampletypecode species                                  
0000      72798    CNEG           Eohaustorius estuarius               1   

                                                         pvalue  mean  \
stationid toxbatch sampletypecode species                               
0000      72798    CNEG           Eohaustorius estuarius    0.5  97.0   

                                                         control_mean  \
stationid toxbatch sampletypecode species                               
0000      72798    CNEG           Eohaustorius estuarius         97.0   

                                                         pctcontrol    stddev  \
stationid toxbatch sampletypecode species                                       
0000      72798    CNEG           Eohaustorius estuarius      100.0  4.472136   

                                                         coefficientvariance  \
stationid toxbatch sampletypecode species                                      
0000      72798    CNEG           Eohaustorius estuarius            0.046104   

                                                          ...       units  \
stationid toxbatch sampletypecode species                 ...               
0000      72798    CNEG           Eohaustorius estuarius  ...  percentage   

                                                         qacode treatment  \
stationid toxbatch sampletypecode species                                   
0000      72798    CNEG           Eohaustorius estuarius      A      None   

                                                         comments  \
stationid toxbatch sampletypecode species                           
0000      72798    CNEG           Eohaustorius estuarius     None   

                                                                  matrix  \
stationid toxbatch sampletypecode species                                  
0000      72798    CNEG           Eohaustorius estuarius  Whole Sediment   

                                                         sigeffect  \
stationid toxbatch sampletypecode species                            
0000      72798    CNEG           Eohaustorius estuarius       NSC   

                                                                         endpoint  \
stationid toxbatch sampletypecode species                                           
0000      72798    CNEG           Eohaustorius estuarius  10 day survival percent   

                                                         sqo_category_value_initial  \
stationid toxbatch sampletypecode species                                             
0000      72798    CNEG           Eohaustorius estuarius                       None   

                                                         Score sqocategory  
stationid toxbatch sampletypecode species                                   
0000      72798    CNEG           Eohaustorius estuarius  None        None  

[1 rows x 21 columns]

In [75]:
unify_2003_correct_.head(1)

surveyyear  \
stationid toxbatch sampletypecode species                              
0000      1        CNEG           Eohaustorius estuarius        2003   

                                                                                                   lab  \
stationid toxbatch sampletypecode species                                                                
0000      1        CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   

                                                         dilution  \
stationid toxbatch sampletypecode species                           
0000      1        CNEG           Eohaustorius estuarius     None   

                                                          fieldreplicate  \
stationid toxbatch sampletypecode species                                  
0000      1        CNEG           Eohaustorius estuarius               1   

                                                         pvalue   mean  \
stationid toxbatch sampletypecode species                                
0000      1        CNEG           Eohaustorius estuarius   None  100.0   

                                                         control_mean  \
stationid toxbatch sampletypecode species                               
0000      1        CNEG           Eohaustorius estuarius        100.0   

                                                         pctcontrol stddev  \
stationid toxbatch sampletypecode species                                    
0000      1        CNEG           Eohaustorius estuarius      100.0    0.0   

                                                         coefficientvariance  \
stationid toxbatch sampletypecode species                                      
0000      1        CNEG           Eohaustorius estuarius                 0.0   

                                                          ...  treatment  \
stationid toxbatch sampletypecode species                 ...              
0000      1        CNEG           Eohaustorius estuarius  ...       None   

                                                         comments matrix  \
stationid toxbatch sampletypecode species                                  
0000      1        CNEG           Eohaustorius estuarius     None   None   

                                                         sigeffect  \
stationid toxbatch sampletypecode species                            
0000      1        CNEG           Eohaustorius estuarius      None   

                                                                         endpoint  \
stationid toxbatch sampletypecode species                                           
0000      1        CNEG           Eohaustorius estuarius  10 day survival percent   

                                                         sqo_category_value_initial  \
stationid toxbatch sampletypecode species                                             
0000      1        CNEG           Eohaustorius estuarius                       None   

                                                         Score sqocategory  \
stationid toxbatch sampletypecode species                                    
0000      1        CNEG           Eohaustorius estuarius  None        None   

                                                         unify_comment  \
stationid toxbatch sampletypecode species                                
0000      1        CNEG           Eohaustorius estuarius          None   

                                                         unify_action  
stationid toxbatch sampletypecode species                              
0000      1        CNEG           Eohaustorius estuarius         None  

[1 rows x 23 columns]

In [76]:
unify_2008_correct_.head(1)

surveyyear  \
stationid toxbatch       sampletypecode species                              
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius        2008   

                                                                                                         lab  \
stationid toxbatch       sampletypecode species                                                                
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius  Aquatic Bioassay and Consulting Laboratories   

                                                               dilution  \
stationid toxbatch       sampletypecode species                           
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius     None   

                                                                fieldreplicate  \
stationid toxbatch       sampletypecode species                                  
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius               1   

                                                               pvalue  mean  \
stationid toxbatch       sampletypecode species                               
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius    0.5  94.0   

                                                               control_mean  \
stationid toxbatch       sampletypecode species                               
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius         94.0   

                                                               pctcontrol  \
stationid toxbatch       sampletypecode species                             
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius      100.0   

                                                                stddev  \
stationid toxbatch       sampletypecode species                          
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius  4.1833   

                                                               coefficientvariance  \
stationid toxbatch       sampletypecode species                                      
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius            0.044503   

                                                                ...  \
stationid toxbatch       sampletypecode species                 ...   
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius  ...   

                                                                treatment  \
stationid toxbatch       sampletypecode species                             
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius       None   

                                                               comments  \
stationid toxbatch       sampletypecode species                           
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius     None   

                                                                        matrix  \
stationid toxbatch       sampletypecode species                                  
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius  Whole Sediment   

                                                               sigeffect  \
stationid toxbatch       sampletypecode species                            
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius       NSC   

                                                                               endpoint  \
stationid toxbatch       sampletypecode species                                           
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius  10 day survival percent   

                                                               sqo_category_value_initial  \
stationid toxbatch       sampletypecode species                                             
0000      EOHT 10.3.2008 CNEG           Eohaustorius estuarius                       None   

                                                               Score  \
stationid toxbatch       sampletypecode species        

In [77]:
unify_2013_correct_.head(1)

surveyyear  \
stationid toxbatch  sampletypecode species                                 
0000      B13071613 CNEG           Mytilus galloprovincialis        2013   

                                                                                                       lab  \
stationid toxbatch  sampletypecode species                                                                   
0000      B13071613 CNEG           Mytilus galloprovincialis  Aquatic Bioassay and Consulting Laboratories   

                                                             dilution  \
stationid toxbatch  sampletypecode species                              
0000      B13071613 CNEG           Mytilus galloprovincialis     None   

                                                              fieldreplicate  \
stationid toxbatch  sampletypecode species                                     
0000      B13071613 CNEG           Mytilus galloprovincialis               1   

                                                             pvalue   mean  \
stationid toxbatch  sampletypecode species                                   
0000      B13071613 CNEG           Mytilus galloprovincialis    0.5  93.15   

                                                             control_mean  \
stationid toxbatch  sampletypecode species                                  
0000      B13071613 CNEG           Mytilus galloprovincialis        93.15   

                                                             pctcontrol  \
stationid toxbatch  sampletypecode species                                
0000      B13071613 CNEG           Mytilus galloprovincialis      100.0   

                                                                stddev  \
stationid toxbatch  sampletypecode species                               
0000      B13071613 CNEG           Mytilus galloprovincialis  2.835692   

                                                             coefficientvariance  \
stationid toxbatch  sampletypecode species                                         
0000      B13071613 CNEG           Mytilus galloprovincialis            0.030442   

                                                              ...  treatment  \
stationid toxbatch  sampletypecode species                    ...              
0000      B13071613 CNEG           Mytilus galloprovincialis  ...       None   

                                                             comments  \
stationid toxbatch  sampletypecode species                              
0000      B13071613 CNEG           Mytilus galloprovincialis     None   

                                                                                matrix  \
stationid toxbatch  sampletypecode species                                               
0000      B13071613 CNEG           Mytilus galloprovincialis  Sediment Water Interface   

                                                             sigeffect  \
stationid toxbatch  sampletypecode species                               
0000      B13071613 CNEG           Mytilus galloprovincialis       NSC   

                                                                          endpoint  \
stationid toxbatch  sampletypecode species                                           
0000      B13071613 CNEG           Mytilus galloprovincialis  Percent normal-alive   

                                                             sqo_category_value_initial  \
stationid toxbatch  sampletypecode species                                                
0000      B13071613 CNEG           Mytilus galloprovincialis                       None   

                                                             Score  \
stationid toxbatch  sampletypecode species                           
0000      B13071613 CNEG           Mytilus galloprovincialis  None   

                                                             sqocategory  \
stationid toxbatch  sampletypecode species                                 
0000      B13071613 C

In [78]:
unify_2018_correct_.head(1)

surveyyear  \
stationid toxbatch                       sampletypecode species                              
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius        2018   

                                                                                                           lab  \
stationid toxbatch                       sampletypecode species                                                  
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius  AMEC, Foster, & Wheeler / WOOD   

                                                                               dilution  \
stationid toxbatch                       sampletypecode species                           
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius     None   

                                                                                fieldreplicate  \
stationid toxbatch                       sampletypecode species                                  
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius               1   

                                                                               pvalue  \
stationid toxbatch                       sampletypecode species                         
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius    0.5   

                                                                                mean  \
stationid toxbatch                       sampletypecode species                        
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius  97.0   

                                                                               control_mean  \
stationid toxbatch                       sampletypecode species                               
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius         97.0   

                                                                               pctcontrol  \
stationid toxbatch                       sampletypecode species                             
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius      100.0   

                                                                                  stddev  \
stationid toxbatch                       sampletypecode species                            
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius  4.472136   

                                                                               coefficientvariance  \
stationid toxbatch                       sampletypecode species                                      
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius            0.046104   

                                                                                ...  \
stationid toxbatch                       sampletypecode species                 ...   
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius  ...   

                                                                                     units  \
stationid toxbatch                       sampletypecode species                              
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius  percentage   

                                                                               qacode  \
stationid toxbatch                       sampletypecode species                         
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius      A   

                                                                               treatment  \
stationid toxbatch                       sampletypecode species                            
0000      18-07-003 to-006; -011 to -014 CNEG           Eohaustorius estuarius      None   

                                                                               comments  \
stationid toxbatch   

In [79]:
unify_2023_correct_.head(1)

surveyyear  \
stationid toxbatch sampletypecode species                                 
0000      ABC001   CNEG           Mytilus galloprovincialis        2023   

                                                                                                      lab  \
stationid toxbatch sampletypecode species                                                                   
0000      ABC001   CNEG           Mytilus galloprovincialis  Aquatic Bioassay and Consulting Laboratories   

                                                            dilution  \
stationid toxbatch sampletypecode species                              
0000      ABC001   CNEG           Mytilus galloprovincialis     None   

                                                             fieldreplicate  \
stationid toxbatch sampletypecode species                                     
0000      ABC001   CNEG           Mytilus galloprovincialis               1   

                                                            pvalue   mean  \
stationid toxbatch sampletypecode species                                   
0000      ABC001   CNEG           Mytilus galloprovincialis    0.5  96.94   

                                                            control_mean  \
stationid toxbatch sampletypecode species                                  
0000      ABC001   CNEG           Mytilus galloprovincialis        96.94   

                                                            pctcontrol  \
stationid toxbatch sampletypecode species                                
0000      ABC001   CNEG           Mytilus galloprovincialis      100.0   

                                                               stddev  \
stationid toxbatch sampletypecode species                               
0000      ABC001   CNEG           Mytilus galloprovincialis  1.944994   

                                                            coefficientvariance  \
stationid toxbatch sampletypecode species                                         
0000      ABC001   CNEG           Mytilus galloprovincialis            0.020064   

                                                             ...       units  \
stationid toxbatch sampletypecode species                    ...               
0000      ABC001   CNEG           Mytilus galloprovincialis  ...  percentage   

                                                            qacode treatment  \
stationid toxbatch sampletypecode species                                      
0000      ABC001   CNEG           Mytilus galloprovincialis      A      None   

                                                            comments  \
stationid toxbatch sampletypecode species                              
0000      ABC001   CNEG           Mytilus galloprovincialis     None   

                                                                               matrix  \
stationid toxbatch sampletypecode species                                               
0000      ABC001   CNEG           Mytilus galloprovincialis  Sediment Water Interface   

                                                            sigeffect  \
stationid toxbatch sampletypecode species                               
0000      ABC001   CNEG           Mytilus galloprovincialis       NSC   

                                                                         endpoint  \
stationid toxbatch sampletypecode species                                           
0000      ABC001   CNEG           Mytilus galloprovincialis  Percent normal-alive   

                                                            sqocategory  \
stationid toxbatch sampletypecode species                                 
0000      ABC001   CNEG           Mytilus galloprovincialis        None   

                                                            unify_comment  \
stationid toxbatch sampletypecode species                                   
0000      ABC001   CNEG           Mytilus galloprovincialis          None  

In [82]:
unify_complete = pd.concat([
    unify_1994_correct_,
    unify_1998_correct_,
    unify_2003_correct_,
    unify_2008_correct_,
    unify_2013_correct_,
    unify_2018_correct_,
    unify_2023_correct_
])
print(unify_complete.reset_index().stationid.isnull().value_counts())
unify_complete = unify_complete.reset_index()
unify_complete.index = unify_complete.index.rename('objectid') + 1
unify_complete = unify_complete.replace(np.nan, None)

stationid
False    4906
Name: count, dtype: int64


stationid                toxbatch sampletypecode  \
objectid                                                     
1              0016                  940939         Result   
2              0032                  940939         Result   
3              0115                  940939         Result   
4              0150                  940939         Result   
5              0365                  940939         Result   
...             ...                     ...            ...   
4902      B23-12363  23-10-019 to 23-10-033         Result   
4903      B23-12366       23-10-001 to -018         Result   
4904      B23-12366  23-10-019 to 23-10-033         Result   
4905      B23-12841       23-09-001 to -018         Result   
4906      B23-12841  23-09-019 to 23-09-036         Result   

                            species  surveyyear  \
objectid                                          
1                  Ampelisca abdita        1994   
2                  Ampelisca abdita        1994   
3                  Ampelisca abdita        1994   
4                  Ampelisca abdita        1994   
5                  Ampelisca abdita        1994   
...                             ...         ...   
4902      Mytilus galloprovincialis        2023   
4903         Eohaustorius estuarius        2023   
4904      Mytilus galloprovincialis        2023   
4905         Eohaustorius estuarius        2023   
4906      Mytilus galloprovincialis        2023   

                                               lab dilution  fieldreplicate  \
objectid                                                                      
1         Science Applications International Corp.     None               1   
2         Science Applications International Corp.     None               1   
3         Science Applications International Corp.     None               1   
4         Science Applications International Corp.     None               1   
5         Science Applications International Corp.     None               1   
...                                            ...      ...             ...   
4902                                           WSP     None               1   
4903                                           WSP     None               1   
4904                                           WSP     None               1   
4905                                           WSP     None               1   
4906                                           WSP     None               1   

            pvalue    mean  ... treatment  \
objectid                    ...             
1          0.08658    90.0  ...      None   
2         0.158067    94.0  ...      None   
3         0.036322    92.0  ...      None   
4         0.222882    93.0  ...      None   
5         0.015915    91.0  ...      None   
...            ...     ...  ...       ...   
4902      0.464153  88.956  ...      None   
4903      0.008065    92.0  ...      None   
4904      0.095549  84.444  ...      None   
4905      0.064819    93.0  ...      None   
4906      0.013521  78.044  ...      None   

                                                   comments  \
objectid                                                      
1                                                      None   
2                                                      None   
3                                                      None   
4                                                      None   
5                                                      None   
...                                                     ...   
4902      Replicate equilibrated an additional 24 hours ...   
4903                                     Salinity at 17 ppt   
4904      Replicate equilibrated an additional 24 hours ...   
4905                                                   None   
4906                                                   None   

                            matrix sigeffect                 endpoint  \
objectid                        

# Write to Excel file

In [85]:
unify_complete.to_excel("unified_complete.xlsx")

# Write Data to Local Database

This is a Postgres database local to my own host. I am using this for final inspection.

In [83]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg://addison:@localhost/addison")

with engine.begin() as con:
    unify_complete.to_sql("summary_corrections", con, schema="unified", if_exists="replace")